#!/bin/sh
aok_repo_files(){ r=$(active_rootfs); find "$r/etc" -maxdepth 4 -type f \( -name 'sources.list' -o -name '*.list' -o -name '*.sources' -o -name repositories -o -name mirrorlist -o -name '*.repo' \) 2>/dev/null; }
aok_repo_view(){ ui_text Repositories "$(aok_repo_files | while read f; do echo "--- $f"; sed -n '1,120p' "$f"; done)"; }
aok_repo_defaults(){ r=$(active_rootfs); os=$(aok_root_os "$r"); case $os in *Devuan*) rel=$(ui_input Devuan 'Release:' excalibur) || return; body="deb https://deb.devuan.org/merged $rel main contrib non-free non-free-firmware\ndeb https://deb.devuan.org/merged $rel-updates main contrib non-free non-free-firmware\ndeb https://deb.devuan.org/merged $rel-security main contrib non-free non-free-firmware"; write_file "$r/etc/apt/sources.list" 644 "$body";; *Debian*) rel=$(ui_input Debian 'Release:' trixie) || return; body="deb https://deb.debian.org/debian $rel main contrib non-free non-free-firmware\ndeb https://security.debian.org/debian-security $rel-security main contrib non-free non-free-firmware\ndeb https://deb.debian.org/debian $rel-updates main contrib non-free non-free-firmware"; write_file "$r/etc/apt/sources.list" 644 "$body";; *Alpine*) branch=$(ui_input Alpine 'Branch:' v3.23) || return; body="https://dl-cdn.alpinelinux.org/alpine/$branch/main\nhttps://dl-cdn.alpinelinux.org/alpine/$branch/community"; write_file "$r/etc/apk/repositories" 644 "$body";; *) ui_msg Repositories 'Use raw repository editor for this distribution.';; esac; }
aok_repo_test(){ aok_repo_files | while read f; do grep -Eo 'https?://[^ /]+' "$f"; done | sort -u | while read u; do if have curl; then curl -LIs --max-time 10 "$u" | head -n1; elif have wget; then wget -S --spider -T 10 "$u" 2>&1 | grep 'HTTP/' | tail -n1; fi; echo "$u"; done >"$REPORT_DIR/aok-repo-test.txt"; ui_text Repositories "$(cat "$REPORT_DIR/aok-repo-test.txt")"; }
aok_init_detect(){ r=$(active_rootfs); { for x in sbin/init bin/busybox sbin/openrc sbin/runit-init lib/systemd/systemd; do [ -e "$r/$x" ] && ls -l "$r/$x"; done; find "$r/etc" -maxdepth 3 -type d \( -name 'runlevels' -o -name 'rc?.d' -o -name systemd \) 2>/dev/null; } >"$REPORT_DIR/aok-init.txt"; ui_text Init "$(cat "$REPORT_DIR/aok-init.txt")"; }
aok_init_sysv(){ aok_confirm 'Install SysVinit and remove systemd-sysv where supported?' || return; pm=$(aok_pkg_manager_detect); case $pm in apt-get) aok_run_in_root apt-get install sysvinit-core sysvinit-utils initscripts; aok_run_in_root apt-get remove systemd-sysv;; apk) aok_run_in_root apk add openrc;; *) ui_msg Init 'No automatic adapter. Use package manager module.';; esac; }
aok_init_inittab(){ r=$(active_rootfs); body='id:3:initdefault:\nsi::sysinit:/etc/init.d/rcS\nl0:0:wait:/etc/init.d/rc 0\nl1:1:wait:/etc/init.d/rc 1\nl2:2:wait:/etc/init.d/rc 2\nl3:3:wait:/etc/init.d/rc 3\nl4:4:wait:/etc/init.d/rc 4\nl5:5:wait:/etc/init.d/rc 5\nl6:6:wait:/etc/init.d/rc 6\nz6:6:respawn:/sbin/sulogin\nca:12345:ctrlaltdel:/sbin/shutdown -t1 -a -r now'; write_file "$r/etc/inittab" 644 "$body"; }
aok_systemd_report(){ r=$(active_rootfs); grep -RIl 'systemctl\|/run/systemd\|libsystemd' "$r/etc" "$r/usr/lib" 2>/dev/null | head -n 300 >"$REPORT_DIR/aok-systemd-requirements.txt"; ui_text systemd "$(cat "$REPORT_DIR/aok-systemd-requirements.txt")"; }
aok_ssh_install(){ pm=$(aok_pkg_manager_detect); case $pm in apt-get) aok_run_in_root apt-get install openssh-server openssh-client;; apk) aok_run_in_root apk add openssh-server openssh-client;; pacman) aok_run_in_root pacman -S openssh;; dnf) aok_run_in_root dnf install openssh-server openssh-clients;; esac; }
aok_ssh_config(){ r=$(active_rootfs); f=$r/etc/ssh/sshd_config; port=$(ui_input SSH 'Port:' 2222) || return; root=$(ui_menu SSH 'Root login' prohibit-password prohibit-password yes yes no no) || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; pass=$(ui_menu SSH 'Password authentication' yes yes no no) || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; body="Port $port\nPermitRootLogin $root\nPasswordAuthentication $pass\nPubkeyAuthentication yes\nClientAliveInterval 60\nClientAliveCountMax 5\nUseDNS no\nSubsystem sftp internal-sftp"; replace_block "$f" aok-ssh "$body"; }
aok_ssh_keys(){ r=$(active_rootfs); aok_chroot_mounts; run_capture SSH as_root chroot "$r" ssh-keygen -A; }
aok_ssh_start(){ r=$(active_rootfs); for cmd in '/etc/init.d/ssh restart' 'rc-service sshd restart' 'service ssh restart' '/usr/sbin/sshd'; do as_root chroot "$r" /bin/sh -c "$cmd" >/tmp/aok-ssh.$$ 2>&1 && { ui_text SSH "$(cat /tmp/aok-ssh.$$)"; rm -f /tmp/aok-ssh.$$; return; }; done; ui_text SSH "$(cat /tmp/aok-ssh.$$ 2>/dev/null)"; rm -f /tmp/aok-ssh.$$; }
aok_repos_init_ssh_menu(){ while :; do c=$(ui_menu 'Repositories, init & SSH' "Active: $(active_rootfs)" repoview 'View repository files' repodefault 'Generate official repository defaults' repoedit 'Edit selected repository file' repotest 'Test repository reachability' repoupdate 'Rebuild package indexes' keyrings 'Inspect signing tools and keyrings' initdetect 'Detect init and service layout' sysv 'Install/convert to SysVinit or OpenRC' inittab 'Generate /etc/inittab' systemd 'Report systemd dependencies' sshinstall 'Install OpenSSH server/client' sshconfig 'Configure SSH in TUI' sshkeys 'Generate host keys' sshvalidate 'Validate sshd configuration' sshstart 'Start/restart SSH' sshcommand 'Generate connection command') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in repoview) aok_repo_view;; repodefault) aok_repo_defaults;; repoedit) f=$(ui_input Repo 'Repository file:' "$(aok_repo_files|head -n1)") || continue; edit_file "$f";; repotest) aok_repo_test;; repoupdate) aok_pkg_indexes;; keyrings) aok_pkg_keys;; initdetect) aok_init_detect;; sysv) aok_init_sysv;; inittab) aok_init_inittab;; systemd) aok_systemd_report;; sshinstall) aok_ssh_install;; sshconfig) aok_ssh_config;; sshkeys) aok_ssh_keys;; sshvalidate) r=$(active_rootfs); run_capture SSH as_root chroot "$r" /usr/sbin/sshd -t;; sshstart) aok_ssh_start;; sshcommand) p=$(grep -E '^Port ' "$(active_rootfs)/etc/ssh/sshd_config" 2>/dev/null|tail -1|awk '{print $2}'); ui_text SSH "ssh -p ${p:-22} root@<iSH-address>";; esac; done; }
