#!/bin/sh
aok_chroot_mounts(){ r=$(active_rootfs); [ "$r" != / ] || return; need_root || return; as_root mkdir -p "$r/dev" "$r/dev/pts" "$r/proc" "$r/sys" "$r/run"; aok_mountpoint "$r/dev" || as_root mount --rbind /dev "$r/dev" 2>/dev/null || as_root mount -o bind /dev "$r/dev"; aok_mountpoint "$r/proc" || as_root mount -t proc proc "$r/proc"; aok_mountpoint "$r/sys" || as_root mount --rbind /sys "$r/sys" 2>/dev/null || true; aok_mountpoint "$r/run" || as_root mount --bind /run "$r/run" 2>/dev/null || true; [ -e "$r/etc/resolv.conf" ] && backup_file "$r/etc/resolv.conf"; [ -r /etc/resolv.conf ] && as_root cp /etc/resolv.conf "$r/etc/resolv.conf"; ui_msg Mounts 'Chroot virtual filesystems prepared.'; }
aok_chroot_unmounts(){ r=$(active_rootfs); [ "$r" != / ] || return; for m in run sys proc dev/pts dev; do aok_mountpoint "$r/$m" && as_root umount -l "$r/$m" 2>/dev/null || true; done; ui_msg Mounts 'Cleanup attempted in reverse order.'; }
aok_chroot_enter(){ r=$(active_rootfs); [ "$r" != / ] || return; aok_chroot_mounts || return; shell=$(ui_menu Shell 'Select shell' bash /bin/bash sh /bin/sh ash /bin/ash zsh /bin/zsh) || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; [ -x "$r$shell" ] || shell=/bin/sh; as_root chroot "$r" "$shell"; }
aok_chroot_processes(){ r=$(active_rootfs); if have lsof; then run_capture Processes lsof +D "$r"; elif have fuser; then run_capture Processes fuser -vm "$r"; else ui_msg Processes 'Install lsof or psmisc/fuser.'; fi; }
aok_chroot_kill(){ r=$(active_rootfs); aok_confirm "Kill processes using $r?" || return; have fuser && as_root fuser -km "$r"; }
aok_chroot_helper(){ r=$(active_rootfs); body="#!/bin/sh\nROOT='${r}'\nmount --rbind /dev \"\$ROOT/dev\" 2>/dev/null || mount -o bind /dev \"\$ROOT/dev\"\nmount -t proc proc \"\$ROOT/proc\" 2>/dev/null || true\nmount --rbind /sys \"\$ROOT/sys\" 2>/dev/null || true\nmount --bind /run \"\$ROOT/run\" 2>/dev/null || true\ncp /etc/resolv.conf \"\$ROOT/etc/resolv.conf\" 2>/dev/null || true\nchroot \"\$ROOT\" /bin/sh\nfor m in run sys proc dev/pts dev; do umount -l \"\$ROOT/\$m\" 2>/dev/null || true; done"; aok_write_script "aok-chroot-$(root_label)" "$body"; }
aok_mount_report(){ r=$(active_rootfs); ui_text Mounts "$(grep " $r" /proc/mounts 2>/dev/null)"; }
aok_chroot_menu(){ while :; do c=$(ui_menu 'Chroot & virtual mounts' "Active: $(active_rootfs)" select 'Select rootfs' mount 'Mount /dev, /proc, /sys and /run' enter 'Mount and enter chroot' report 'Show rootfs-related mounts' processes 'Show processes using rootfs' kill 'Kill remaining rootfs processes' unmount 'Unmount in reverse order' force 'Force lazy cleanup' helper 'Generate reusable launcher' readonly 'Generate read-only chroot helper' profiles 'Manage rootfs mount profiles' custom 'Configure custom bind mounts') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in select) aok_select_root;; mount) aok_chroot_mounts;; enter) aok_chroot_enter;; report) aok_mount_report;; processes) aok_chroot_processes;; kill) aok_chroot_kill;; unmount|force) aok_chroot_unmounts;; helper) aok_chroot_helper;; profiles) mount_profiles_menu rootfs;; readonly) ui_msg Read-only 'Use bind mounts with remount,ro only where supported. iSH-AOK may not support all remount semantics.';; custom) edit_file "$AOK_STATE_DIR/custom-mounts.conf";; esac; done; }
