#!/bin/sh
aok_build_profile_file(){ printf '%s/build.profile' "$AOK_PROFILE_DIR"; }
aok_build_profile_edit(){ f=$(aok_build_profile_file); [ -f "$f" ] || write_file "$f" 644 "DISTRO=devuan\nRELEASE=excalibur\nARCH=arm64\nDEST=/AOK/roots/Devuan-excalibur-arm64\nMIRROR=\nPACKAGES=\nINIT=sysvinit\nHOSTNAME=ish-aok\nUSER_NAME=user\nSHELL_PATH=/bin/bash\nLOCALE=C.UTF-8\nTIMEZONE=UTC\nENABLE_SSH=yes\nCOMPRESSION=zstd"; edit_file "$f"; }
aok_build_show(){ f=$(aok_build_profile_file); [ -f "$f" ] || aok_build_profile_edit; ui_text 'Build profile' "$(cat "$f")"; }
aok_builder_debootstrap(){ have debootstrap || { aok_install_hint debootstrap; return; }; f=$(aok_build_profile_file); [ -r "$f" ] && . "$f"; rel=${RELEASE:-stable}; dest=${DEST:-/AOK/roots/debian-rootfs}; arch=${ARCH:-arm64}; mirror=${MIRROR:-}; cmd="debootstrap --arch=$arch $rel '$dest'${mirror:+ '$mirror'}"; aok_command_preview "$cmd"; aok_confirm 'Run debootstrap builder?' && run_capture Debootstrap sh -c "$cmd"; }
aok_builder_apk(){ have apk || { aok_install_hint apk; return; }; dest=$(ui_input Alpine 'Destination:' '/AOK/roots/alpine-rootfs') || return; branch=$(ui_input Alpine 'Branch:' 'latest-stable') || return; mirror=$(ui_input Alpine 'Mirror:' 'https://dl-cdn.alpinelinux.org/alpine') || return; cmd="mkdir -p '$dest/etc/apk' && echo '$mirror/$branch/main' > '$dest/etc/apk/repositories' && apk --root '$dest' --initdb add alpine-base"; aok_command_preview "$cmd"; aok_confirm 'Build Alpine rootfs?' && run_capture Alpine as_root sh -c "$cmd"; }
aok_builder_pacstrap(){ have pacstrap || { aok_install_hint pacstrap; return; }; dest=$(ui_input Arch 'Destination:' '/AOK/roots/arch-rootfs') || return; aok_confirm 'Run pacstrap base installation?' && run_capture Arch as_root pacstrap -c "$dest" base bash; }
aok_builder_dnf(){ have dnf || { aok_install_hint dnf; return; }; dest=$(ui_input DNF 'Destination:' '/AOK/roots/fedora-rootfs') || return; rel=$(ui_input DNF 'Release version:' 'latest') || return; cmd="dnf -y --releasever='$rel' --installroot='$dest' --setopt=install_weak_deps=False install @core"; aok_command_preview "$cmd"; aok_confirm 'Run DNF installroot?' && run_capture DNF as_root sh -c "$cmd"; }
aok_builder_xbps(){ have xbps-install || { aok_install_hint xbps-install; return; }; dest=$(ui_input XBPS 'Destination:' '/AOK/roots/void-rootfs') || return; repo=$(ui_input XBPS 'Repository URL:' 'https://repo-default.voidlinux.org/current/aarch64') || return; aok_confirm 'Build Void rootfs?' && run_capture XBPS as_root env XBPS_ARCH=aarch64 xbps-install -Sy -R "$repo" -r "$dest" base-system; }
aok_import_directory(){ src=$(ui_input Import 'Existing rootfs directory:' '') || return; dst=$(ui_input Import 'Destination:' "/AOK/roots/$(basename "$src")") || return; [ -d "$src" ] || return; aok_confirm "Import $src to $dst?" || return; if have rsync; then run_capture Import as_root rsync -aH "$src/" "$dst/"; else run_capture Import as_root cp -a "$src" "$dst"; fi; }
aok_build_fs_wrapper(){ b=''; for x in /opt/AOK/build_fs /AOK/build_fs; do [ -x "$x" ] && b=$x; done; [ -n "$b" ] || { ui_msg build_fs 'build_fs was not found.'; return; }; args=$(ui_input build_fs 'Arguments:' '-D') || return; aok_command_preview "$b $args"; aok_confirm 'Run build_fs?' && run_capture build_fs sh -c "'$b' $args"; }
aok_build_logs(){ f=$(find /opt/AOK /AOK /tmp -type f \( -name '*.log' -o -name '*build*log*' \) 2>/dev/null | tail -n 20); ui_text 'Build logs' "$f"; }
aok_build_clean(){ d=$(ui_input Clean 'Failed build directory:' '') || return; [ -d "$d" ] || return; aok_confirm "Delete failed build directory $d?" && as_root rm -rf "$d"; }
aok_build_menu(){ while :; do c=$(ui_menu 'AOK builders & importers' 'Profiles, previews and multi-distribution rootfs creation.' profile 'Edit build profile' show 'Show current build profile' buildfs 'Run /opt/AOK/build_fs wrapper' debootstrap 'Debian/Devuan/Ubuntu debootstrap' apk 'Alpine apk --root builder' pacstrap 'Arch pacstrap builder' dnf 'Fedora/Ultramarine DNF installroot' xbps 'Void XBPS rootfs builder' stage3 'Gentoo stage3/custom tarball importer' directory 'Existing-directory importer' logs 'Find and inspect build logs' clean 'Clean failed build directory' shell 'Open shell in build directory') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in profile) aok_build_profile_edit;; show) aok_build_show;; buildfs) aok_build_fs_wrapper;; debootstrap) aok_builder_debootstrap;; apk) aok_builder_apk;; pacstrap) aok_builder_pacstrap;; dnf) aok_builder_dnf;; xbps) aok_builder_xbps;; stage3) aok_fs_extract;; directory) aok_import_directory;; logs) aok_build_logs;; clean) aok_build_clean;; shell) d=$(ui_input Shell 'Build directory:' /opt/AOK) || continue; (cd "$d" && ${SHELL:-/bin/sh});; esac; done; }
