#!/bin/sh
aok_fs_list(){ out=$(aok_report_file filesystems); { printf '%-45s %-24s %s\n' PATH DISTRIBUTION SIZE; aok_find_roots | while read r; do [ -n "$r" ] || continue; s=$(du -sh "$r" 2>/dev/null|awk '{print $1}'); printf '%-45s %-24s %s\n' "$r" "$(aok_root_os "$r")" "${s:-?}"; done; } >"$out"; ui_text Filesystems "$(cat "$out")"; }
aok_fs_clone(){ src=$(active_rootfs); [ "$src" != / ] || { ui_msg Clone 'Select a non-host rootfs.'; return; }; dst=$(ui_input Clone 'Destination directory:' "${src}-clone") || return; aok_confirm "Clone $src to $dst?" || return; [ ! -e "$dst" ] || { ui_msg Clone 'Destination exists.'; return; }; if have rsync; then run_capture Clone as_root rsync -aHAX --numeric-ids "$src/" "$dst/"; else run_capture Clone as_root cp -a "$src" "$dst"; fi; }
aok_fs_rename(){ src=$(active_rootfs); [ "$src" != / ] || return; dst=$(ui_input Rename 'New path:' "$(dirname "$src")/new-$(basename "$src")") || return; aok_confirm "Rename $src to $dst?" || return; as_root mv "$src" "$dst" && set_active_rootfs "$dst"; }
aok_fs_delete(){ r=$(active_rootfs); [ "$r" != / ] || return; aok_confirm "PERMANENTLY delete $r?" || return; aok_confirm 'This cannot be undone unless you have a snapshot. Continue?' || return; as_root rm -rf -- "$r" && set_active_rootfs /; }
aok_fs_archive(){ r=$(active_rootfs); [ "$r" != / ] || { ui_msg Archive 'Select a non-host rootfs.'; return; }; fmt=$(ui_menu Archive 'Compression format' gz 'gzip (.tar.gz)' xz 'xz (.tar.xz)' zst 'zstd (.tar.zst)' none 'uncompressed tar') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; base=$(basename "$r"); out=$(ui_input Archive 'Output path:' "$CURRENT_HOME/$base.tar.$fmt") || return; case $fmt in gz) cmd="tar -czf '$out' -C '$(dirname "$r")' '$base'";; xz) cmd="tar -cJf '$out' -C '$(dirname "$r")' '$base'";; zst) cmd="tar --zstd -cf '$out' -C '$(dirname "$r")' '$base'";; none) cmd="tar -cf '$out' -C '$(dirname "$r")' '$base'";; esac; aok_command_preview "$cmd"; aok_confirm 'Create archive?' && run_capture Archive sh -c "$cmd"; }
aok_fs_extract(){ a=$(ui_input Extract 'Archive path:' '') || return; d=$(ui_input Extract 'Destination directory:' '/AOK/roots') || return; [ -f "$a" ] || return; as_root mkdir -p "$d"; run_capture Extract as_root tar -xaf "$a" -C "$d"; }
aok_fs_verify(){ a=$(ui_input Verify 'Archive path:' '') || return; run_capture Verify tar -taf "$a"; }
aok_fs_compare(){ a=$(active_rootfs); b=$(ui_input Compare 'Other rootfs:' '') || return; [ -d "$b" ] || return; if have diff; then run_capture Compare diff -qr "$a" "$b"; else aok_install_hint diff; fi; }
aok_fs_repair_layout(){ r=$(active_rootfs); aok_confirm "Create missing standard directories under $r?" || return; for d in bin boot dev etc home lib lib64 media mnt opt proc root run sbin srv sys tmp usr var; do [ -d "$r/$d" ] || as_root mkdir -p "$r/$d"; done; as_root chmod 1777 "$r/tmp" 2>/dev/null || true; ui_msg Repair 'Standard directory check complete.'; }
aok_fs_permissions(){ r=$(active_rootfs); aok_confirm "Repair common ownership and permissions in $r?" || return; as_root chmod 755 "$r" "$r/etc" "$r/usr" "$r/var" 2>/dev/null || true; as_root chmod 1777 "$r/tmp" 2>/dev/null || true; [ -d "$r/root" ] && as_root chmod 700 "$r/root"; [ -d "$r/etc/ssh" ] && as_root chmod 755 "$r/etc/ssh"; ui_msg Repair 'Common permissions repaired.'; }
aok_filesystems_menu(){ while :; do c=$(ui_menu 'AOK filesystem lifecycle' "Active: $(active_rootfs)" list 'List roots, distributions and sizes' select 'Select active rootfs' clone 'Clone active rootfs' rename 'Rename active rootfs' delete 'Delete active rootfs' archive 'Archive/compress rootfs' extract 'Extract/import archive' verify 'Verify archive contents' compare 'Compare two rootfs trees' inventory 'Export package inventory' repairlayout 'Repair standard directory layout' permissions 'Repair common permissions' duplicates 'Find duplicate files' integrity 'Filesystem integrity checks') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in list) aok_fs_list;; select) aok_select_root;; clone) aok_fs_clone;; rename) aok_fs_rename;; delete) aok_fs_delete;; archive) aok_fs_archive;; extract) aok_fs_extract;; verify) aok_fs_verify;; compare) aok_fs_compare;; inventory) aok_pkg_inventory;; repairlayout) aok_fs_repair_layout;; permissions) aok_fs_permissions;; duplicates) aok_storage_duplicates;; integrity) aok_fs_diagnostics;; esac; done; }
