#!/bin/sh
aok_size_report(){ r=$(active_rootfs); out=$(aok_report_file sizes); du -x -h "$r" 2>/dev/null | sort -h | tail -n 200 >"$out"; ui_text Sizes "$(cat "$out")"; }
aok_optimize_clean(){ r=$(active_rootfs); aok_confirm 'Remove package caches, temporary files and stale logs?' || return; aok_backup_root_config >/dev/null 2>&1 || true; for d in var/cache/apt/archives var/cache/apk var/cache/pacman/pkg var/cache/dnf var/tmp tmp; do [ -d "$r/$d" ] && as_root find "$r/$d" -mindepth 1 -maxdepth 1 -exec rm -rf {} +; done; [ -d "$r/var/log" ] && as_root find "$r/var/log" -type f -name '*.log' -size +0 -exec sh -c ': > "$1"' _ {} \;; }
aok_optimize_docs(){ r=$(active_rootfs); aok_confirm 'Remove documentation, manpages and info files?' || return; for d in usr/share/doc usr/share/man usr/share/info; do [ -d "$r/$d" ] && as_root rm -rf "$r/$d"/*; done; }
aok_optimize_systemd(){ r=$(active_rootfs); aok_confirm 'Remove obvious systemd cache/runtime remnants only? Packages will not be removed.' || return; for d in var/lib/systemd/coredump var/log/journal run/systemd; do [ -e "$r/$d" ] && as_root rm -rf "$r/$d"; done; }
aok_strip(){ r=$(active_rootfs); have strip || { aok_install_hint strip; return; }; aok_confirm 'Strip unstripped ELF binaries and libraries? This can break debugging.' || return; find "$r/bin" "$r/sbin" "$r/usr/bin" "$r/usr/sbin" "$r/lib" "$r/usr/lib" -type f 2>/dev/null | while read f; do file "$f" 2>/dev/null | grep -q 'ELF.*not stripped' && as_root strip --strip-unneeded "$f" 2>/dev/null || true; done; }
aok_profile_apply(){ p=$(ui_menu Profile 'Optimization profile' minimal 'Minimal runtime' ssh 'SSH-only' developer Developer lowmem 'Low memory') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $p in minimal) aok_optimize_clean; aok_optimize_docs;; ssh) aok_optimize_clean; aok_ssh_install; aok_ssh_config;; developer) aok_pkg_essential;; lowmem) aok_optimize_clean; replace_block "$(active_rootfs)/etc/profile" aok-lowmem 'export MAKEFLAGS="-j1"\nexport CARGO_BUILD_JOBS=1\nexport NINJAFLAGS="-j1"';; esac; }
aok_sync_select(){ src=$(active_rootfs); dst=$(ui_input Sync 'Destination rootfs:' '') || return; [ -d "$dst" ] || return; items=$(ui_checklist Sync 'Select configuration groups' shells 'Shell profiles and rc files' on editors 'Editor configurations' on ssh 'SSH client/server configuration' off repos 'Repository configuration' off locale 'Locale/timezone/hostname' off users 'passwd/group/shadow' off scripts 'Local scripts' off services 'Service configuration' off) || return; snap=$(aok_backup_root_config 2>/dev/null || true); for i in $items; do case $i in shells) for f in root/.profile root/.bashrc root/.zshrc etc/profile; do [ -e "$src/$f" ] && as_root mkdir -p "$dst/$(dirname "$f")" && as_root cp -a "$src/$f" "$dst/$f"; done;; editors) [ -d "$src/root/.config" ] && as_root cp -a "$src/root/.config" "$dst/root/";; ssh) [ -d "$src/etc/ssh" ] && as_root cp -a "$src/etc/ssh" "$dst/etc/";; repos) for f in etc/apt etc/apk etc/pacman.conf etc/yum.repos.d; do [ -e "$src/$f" ] && as_root cp -a "$src/$f" "$dst/$(dirname "$f")/"; done;; locale) for f in etc/locale.conf etc/timezone etc/localtime etc/hostname etc/hosts; do [ -e "$src/$f" ] && as_root cp -a "$src/$f" "$dst/$f"; done;; users) for f in etc/passwd etc/group etc/shadow; do [ -e "$src/$f" ] && as_root cp -a "$src/$f" "$dst/$f"; done;; scripts) [ -d "$src/usr/local/bin" ] && as_root cp -a "$src/usr/local/bin" "$dst/usr/local/";; services) [ -d "$src/etc/init.d" ] && as_root cp -a "$src/etc/init.d" "$dst/etc/";; esac; done; ui_msg Sync "Synchronization complete.\nPre-change snapshot: ${snap:-not created}"; }
aok_optimize_sync_menu(){ while :; do c=$(ui_menu 'Optimization & synchronization' "Active: $(active_rootfs)" sizes 'Largest directories and files' packages 'Largest installed packages' clean 'Clean caches, temporary files and logs' docs 'Remove docs/manpages/info' locales 'Remove unselected locales' firmware 'Remove firmware and hardware utilities' systemd 'Remove systemd runtime remnants' strip 'Strip binaries and libraries' profile 'Apply minimal/SSH/developer/low-memory profile' estimate 'Estimate compressed archive size' sync 'Synchronize selected configuration to another rootfs' migrate 'Create migration bundle' compare 'Compare configurations' dedupe 'Find duplicate files') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in sizes) aok_size_report;; packages) aok_pkg_inventory;; clean) aok_optimize_clean;; docs) aok_optimize_docs;; locales) ui_msg Locales 'Use the distribution locale manager; automatic locale deletion is intentionally conservative.';; firmware) ui_msg Firmware 'Review /usr/lib/firmware and installed package inventory before removal.';; systemd) aok_optimize_systemd;; strip) aok_strip;; profile) aok_profile_apply;; estimate) r=$(active_rootfs); tar -cf - -C "$(dirname "$r")" "$(basename "$r")" 2>/dev/null | gzip -1 | wc -c | awk '{printf "Estimated gzip size: %.1f MiB\n",$1/1048576}' | ui_text Estimate "$(cat)";; sync) aok_sync_select;; migrate) aok_migration_bundle;; compare) compare_rootfs;; dedupe) aok_storage_duplicates;; esac; done; }
aok_storage_duplicates(){ r=$(active_rootfs); out=$(aok_report_file duplicates); if have fdupes; then fdupes -r "$r" >"$out"; else find "$r" -xdev -type f -size +0 -exec cksum {} + 2>/dev/null | sort -k1,2 | awk 'p==$1":"$2{print prev;print $0} {p=$1":"$2;prev=$0}' >"$out"; fi; ui_text Duplicates "$(head -n 400 "$out")"; }
aok_migration_bundle(){ r=$(active_rootfs); o="$CURRENT_HOME/aok-migration-$(root_label)-$(date +%Y%m%d-%H%M%S).tar.gz"; tar -czf "$o" -C "$r" etc root/.profile root/.bashrc root/.zshrc root/.config usr/local/bin 2>/dev/null; ui_msg Migration "$o"; }
