#!/bin/sh
aok_arch_scan(){ r=$(active_rootfs); out=$(aok_report_file architecture); find "$r" -xdev -type f -perm -111 2>/dev/null | while read f; do file "$f" 2>/dev/null | grep -E 'ELF|Mach-O|PE32'; done >"$out"; ui_text Architecture "$(awk -F: '{print $2}' "$out" | sort | uniq -c | sort -nr | head -n 80)"; }
aok_arch_wrong(){ r=$(active_rootfs); expected=$(ui_input Architecture 'Expected architecture token (ARM aarch64 x86-64 80386 RISC-V):' 'ARM aarch64') || return; out=$(aok_report_file incompatible); find "$r" -xdev -type f -perm -111 2>/dev/null | while read f; do x=$(file "$f" 2>/dev/null); echo "$x" | grep -q ELF || continue; echo "$x" | grep -q "$expected" || echo "$x"; done >"$out"; ui_text 'Potentially incompatible binaries' "$(head -n 300 "$out")"; }
aok_dynamic_linker(){ r=$(active_rootfs); out=$(aok_report_file linker); find "$r/lib" "$r/lib64" "$r/usr/lib" -maxdepth 3 -type f -name 'ld-*' -o -name 'ld-linux*' 2>/dev/null >"$out"; for b in "$r/bin/sh" "$r/bin/bash"; do [ -f "$b" ] && readelf -l "$b" 2>/dev/null | grep interpreter; done >>"$out"; ui_text Linker "$(cat "$out")"; }
aok_exec_test(){ r=$(active_rootfs); aok_chroot_mounts; run_capture 'Execution test' as_root chroot "$r" /bin/sh -c 'uname -m; /bin/sh -c "echo execution-ok"; ldd /bin/sh 2>&1 || true'; }
aok_pkg_manager_detect(){ r=$(active_rootfs); for x in apt-get apk pacman dnf xbps-install emerge zypper; do [ -x "$r/usr/bin/$x" ] || [ -x "$r/bin/$x" ] || continue; echo "$x"; return; done; echo unknown; }
aok_pkg_inventory(){ r=$(active_rootfs); out=$(aok_report_file packages); pm=$(aok_pkg_manager_detect); case $pm in apt-get) aok_run_in_root dpkg-query -W >"$out" 2>&1;; apk) aok_run_in_root apk info -vv >"$out" 2>&1;; pacman) aok_run_in_root pacman -Q >"$out" 2>&1;; dnf) aok_run_in_root rpm -qa >"$out" 2>&1;; xbps-install) aok_run_in_root xbps-query -l >"$out" 2>&1;; emerge) aok_run_in_root qlist -Iv >"$out" 2>&1;; *) echo 'Unknown package manager' >"$out";; esac; ui_text Packages "$(head -n 400 "$out")"; }
aok_pkg_repair(){ pm=$(aok_pkg_manager_detect); aok_confirm "Run standard repair for $pm?" || return; case $pm in apt-get) aok_run_in_root dpkg --configure -a; aok_run_in_root apt-get -f install;; apk) aok_run_in_root apk fix;; pacman) aok_run_in_root pacman -Syyu;; dnf) aok_run_in_root rpm --rebuilddb; aok_run_in_root dnf check;; xbps-install) aok_run_in_root xbps-pkgdb -a;; *) ui_msg Repair 'No standard repair adapter is available.';; esac; }
aok_pkg_keys(){ r=$(active_rootfs); out=$(aok_report_file keys); find "$r/etc" "$r/usr/share/keyrings" -type f \( -name '*.gpg' -o -name '*.asc' -o -path '*/apk/keys/*' \) 2>/dev/null >"$out"; ui_text Keyrings "$(cat "$out")"; }
aok_arch_packages_menu(){ while :; do c=$(ui_menu 'Architecture & package repair' "Active: $(active_rootfs) | PM: $(aok_pkg_manager_detect)" scan 'Scan executable architectures' wrong 'Find wrong-architecture binaries' linker 'Dynamic linker and ELF interpreter check' libraries 'Missing shared-library diagnostics' exec 'Test chroot execution' qemu 'Inspect QEMU user emulators' matrix 'Generate compatibility matrix' inventory 'Export installed packages' repair 'Repair interrupted package state' locks 'Clear package-manager locks' keys 'Inspect repository keyrings' indexes 'Rebuild package indexes' essential 'Reinstall essential packages') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in scan) aok_arch_scan;; wrong) aok_arch_wrong;; linker) aok_dynamic_linker;; libraries) aok_missing_libraries;; exec) aok_exec_test;; qemu) run_capture QEMU sh -c 'command -v qemu-aarch64 qemu-x86_64 qemu-i386 qemu-riscv64 2>/dev/null; ls /proc/sys/fs/binfmt_misc 2>/dev/null';; matrix) aok_arch_scan;; inventory) aok_pkg_inventory;; repair) aok_pkg_repair;; locks) aok_clear_pkg_locks;; keys) aok_pkg_keys;; indexes) aok_pkg_indexes;; essential) aok_pkg_essential;; esac; done; }
aok_clear_pkg_locks(){ r=$(active_rootfs); aok_confirm 'Clear known stale package-manager lock files?' || return; for f in var/lib/dpkg/lock var/lib/dpkg/lock-frontend var/cache/apt/archives/lock var/lib/pacman/db.lck var/lib/rpm/.rpm.lock; do [ -e "$r/$f" ] && as_root rm -f "$r/$f"; done; }
aok_pkg_indexes(){ pm=$(aok_pkg_manager_detect); case $pm in apt-get) aok_run_in_root apt-get update;; apk) aok_run_in_root apk update;; pacman) aok_run_in_root pacman -Syy;; dnf) aok_run_in_root dnf makecache;; xbps-install) aok_run_in_root xbps-install -S;; esac; }
aok_pkg_essential(){ pm=$(aok_pkg_manager_detect); p=$(ui_input Packages 'Essential package list:' 'bash coreutils grep sed findutils ca-certificates') || return; case $pm in apt-get) aok_run_in_root apt-get install --reinstall $p;; apk) aok_run_in_root apk fix $p;; pacman) aok_run_in_root pacman -S $p;; dnf) aok_run_in_root dnf reinstall $p;; esac; }
aok_missing_libraries(){ r=$(active_rootfs); out=$(aok_report_file missing-libs); find "$r/bin" "$r/usr/bin" -type f -perm -111 2>/dev/null | head -n 300 | while read f; do chroot "$r" ldd "${f#$r}" 2>/dev/null | grep 'not found' && echo "  in ${f#$r}"; done >"$out"; ui_text Libraries "$(cat "$out")"; }
