#!/bin/sh
aok_rootfs_manifest_export(){ r=$(require_active_rootfs) || return; out=$REPORT_DIR/aok-manifest-$(basename "$r").txt; { echo "rootfs=$r"; echo "generated=$(date)"; echo "architecture=$(aok_rootfs_arch "$r")"; echo; echo '[packages]'; chroot "$r" sh -c 'command -v dpkg-query >/dev/null && dpkg-query -W -f="${Package}\t${Version}\n" || command -v apk >/dev/null && apk info -vv || command -v pacman >/dev/null && pacman -Q || true' 2>/dev/null; echo; echo '[services]'; find "$r/etc/init.d" "$r/etc/sv" "$r/etc/systemd/system" -maxdepth 2 -type f 2>/dev/null | sed "s#^$r##"; echo; echo '[configs]'; find "$r/etc" -maxdepth 2 -type f 2>/dev/null | sort; } >"$out"; ui_text 'Rootfs manifest' "$(cat "$out")"; }
aok_rootfs_health_score(){ r=$(require_active_rootfs) || return; score=100; issues=''; for d in etc usr var tmp dev proc sys; do [ -d "$r/$d" ] || { score=$((score-8)); issues="$issues\nMissing /$d"; }; done; [ -x "$r/bin/sh" ] || { score=$((score-15)); issues="$issues\nMissing executable /bin/sh"; }; [ -f "$r/etc/passwd" ] || { score=$((score-10)); issues="$issues\nMissing /etc/passwd"; }; [ -f "$r/etc/resolv.conf" ] || { score=$((score-4)); issues="$issues\nMissing resolver configuration"; }; find "$r" -xdev -type f -perm -0002 2>/dev/null | head -n 1 | grep . >/dev/null && { score=$((score-5)); issues="$issues\nWorld-writable files detected"; }; ui_msg 'Rootfs health score' "Score: $score/100\nRootfs: $r\n$issues"; }
aok_rootfs_overlay_create(){ r=$(require_active_rootfs) || return; name=$(ui_input Overlay 'Overlay name:' custom) || return; d=$STATE_DIR/aok-overlays/$name; mkdir -p "$d/etc" "$d/usr/local/bin" "$d/root"; cat >"$d/README" <<EOF
Overlay: $name
Copy files into this directory using paths relative to rootfs /. Apply through the AOK menu.
EOF
ui_msg Overlay "Created $d"; }
aok_rootfs_overlay_apply(){ r=$(require_active_rootfs) || return; set --; for d in "$STATE_DIR"/aok-overlays/*; do [ -d "$d" ] || continue; n=${d##*/}; set -- "$@" "$n" "$d"; done; [ $# -gt 0 ] || { ui_msg Overlay 'No overlays exist.'; return; }; n=$(ui_menu 'Apply overlay' "Target: $r" "$@") || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; aok_snapshot_create config pre-overlay >/dev/null 2>&1 || true; cp -a "$STATE_DIR/aok-overlays/$n/." "$r/"; ui_msg Overlay 'Overlay applied.'; }
aok_rootfs_batch_action(){ roots=$(aok_discover_rootfs); [ -n "$roots" ] || return; action=$(ui_menu 'Batch rootfs action' 'Apply an operation to all discovered root filesystems.' inventory 'Export package inventories' dns 'Copy current DNS configuration' clean 'Clean package caches and temporary files' sshkeys 'Generate missing SSH host keys' validate 'Run layout validation' archive 'Create compressed archives') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; printf '%s\n' "$roots" | while IFS= read -r r; do [ -d "$r" ] || continue; case $action in inventory) old=$(active_rootfs); set_active_rootfs "$r"; aok_rootfs_manifest_export >/dev/null;; dns) cp /etc/resolv.conf "$r/etc/resolv.conf" 2>/dev/null || true;; clean) rm -rf "$r/var/cache/apt/archives/"*.deb "$r/var/cache/apk/"* "$r/var/cache/pacman/pkg/"* "$r/tmp/"* 2>/dev/null || true;; sshkeys) chroot "$r" ssh-keygen -A 2>/dev/null || true;; validate) for d in etc usr var tmp; do [ -d "$r/$d" ] || echo "$r missing $d"; done;; archive) tar -C "$r" -czf "$BACKUP_DIR/$(basename "$r")-$(date +%Y%m%d%H%M%S).tar.gz" .;; esac; done; scan_system; }
aok_service_compat_scan(){ r=$(require_active_rootfs) || return; out=$REPORT_DIR/aok-service-compat-$(basename "$r").txt; grep -RIlE 'systemctl|journalctl|systemd-run|loginctl|hostnamectl|timedatectl|udevadm|NetworkManager|modprobe|sysctl|mount -t cgroup' "$r/etc" "$r/usr/local" 2>/dev/null >"$out" || true; ui_text 'AOK service compatibility' "$(cat "$out")"; }
aok_systemctl_wrapper(){ r=$(require_active_rootfs) || return; target=$r/usr/local/bin/systemctl; mkdir -p "$(dirname "$target")"; cat >"$target" <<'EOF'
#!/bin/sh
cmd=${1:-}; svc=${2:-}; svc=${svc%.service}
case $cmd in start|stop|restart|status|reload) [ -x /etc/init.d/$svc ] && exec /etc/init.d/$svc "$cmd";; enable) command -v update-rc.d >/dev/null && exec update-rc.d "$svc" defaults; command -v rc-update >/dev/null && exec rc-update add "$svc" default;; disable) command -v update-rc.d >/dev/null && exec update-rc.d -f "$svc" remove; command -v rc-update >/dev/null && exec rc-update del "$svc" default;; list-units|list-unit-files) find /etc/init.d -maxdepth 1 -type f -printf '%f\n' 2>/dev/null;; esac
echo "systemctl compatibility wrapper: unsupported action: $*" >&2
exit 1
EOF
chmod 755 "$target"; ui_msg AOK "Installed iSH-safe systemctl compatibility wrapper in $r"; }
aok_build_recipe_export(){ r=$(require_active_rootfs) || return; name=$(ui_input 'Build recipe' 'Recipe name:' "$(basename "$r")") || return; f=$STATE_DIR/aok-recipes/$name.recipe; mkdir -p "$(dirname "$f")"; cat >"$f" <<EOF
name=$name
source_rootfs=$r
architecture=$(aok_rootfs_arch "$r")
distribution=$(sed -n 's/^ID=//p' "$r/etc/os-release" 2>/dev/null | tr -d '"')
release=$(sed -n 's/^VERSION_CODENAME=//p' "$r/etc/os-release" 2>/dev/null | tr -d '"')
init=$( [ -x "$r/sbin/init" ] && basename "$(readlink "$r/sbin/init" 2>/dev/null || echo init)" )
packages_file=$REPORT_DIR/aok-manifest-$(basename "$r").txt
compression=zstd
EOF
ui_text 'Build recipe' "$(cat "$f")"; }
aok_emulation_readiness(){ r=$(require_active_rootfs) || return; arch=$(aok_rootfs_arch "$r"); host=$ARCH; q='none'; for x in qemu-aarch64-static qemu-x86_64-static qemu-i386-static qemu-riscv64-static; do have "$x" && q="$q $(command -v "$x")"; done; ui_msg 'Emulation readiness' "Host architecture: $host\nRootfs architecture: $arch\nQEMU static interpreters: $q\n/proc/sys/fs/binfmt_misc: $( [ -d /proc/sys/fs/binfmt_misc ] && echo present || echo unavailable )"; }
aok_more_options_menu(){ while :; do c=$(ui_menu 'Additional AOK tools' "Active rootfs: $(active_rootfs)" health 'Calculate rootfs health score' manifest 'Export complete rootfs manifest' overlays 'Create or apply filesystem overlays' batch 'Batch operations across all rootfs instances' service 'Scan service and kernel-feature compatibility' systemctl 'Install SysV/OpenRC systemctl compatibility wrapper' recipe 'Export reproducible build recipe' emulation 'Check cross-architecture emulation readiness' secrets 'Scan rootfs for likely secrets before export' ownership 'Normalize rootfs ownership for archive/export' compact 'Create compact rootfs copy using rsync exclusions' comparepkgs 'Compare package manifests between two rootfs instances') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in health) aok_rootfs_health_score;; manifest) aok_rootfs_manifest_export;; overlays) x=$(ui_menu Overlay 'Overlay management' create 'Create overlay template' apply 'Apply overlay to active rootfs') || continue; [ "$x" = create ] && aok_rootfs_overlay_create || aok_rootfs_overlay_apply;; batch) aok_rootfs_batch_action;; service) aok_service_compat_scan;; systemctl) aok_systemctl_wrapper;; recipe) aok_build_recipe_export;; emulation) aok_emulation_readiness;; secrets) r=$(require_active_rootfs)||continue; grep -RIlE 'BEGIN (RSA |OPENSSH |EC )?PRIVATE KEY|password[[:space:]]*=|token[[:space:]]*=|secret[[:space:]]*=' "$r/root" "$r/home" "$r/etc" 2>/dev/null >"$REPORT_DIR/aok-secrets.txt" || true; ui_text 'Secret scan' "$(cat "$REPORT_DIR/aok-secrets.txt")";; ownership) r=$(require_active_rootfs)||continue; ui_yesno Ownership 'Set all rootfs files to uid/gid 0? This is intended for exported Linux rootfs archives.' && chown -R 0:0 "$r";; compact) r=$(require_active_rootfs)||continue; d=$(ui_input Compact 'Destination directory:' "$r-compact")||continue; mkdir -p "$d"; rsync -aHAX --numeric-ids --exclude='/var/cache/*' --exclude='/tmp/*' --exclude='/var/log/*.log' "$r/" "$d/";; comparepkgs) aok_compare_package_sets;; esac; done; }
aok_compare_package_sets(){ roots=$(aok_discover_rootfs); set --; printf '%s\n' "$roots" | while IFS= read -r r; do [ -d "$r" ] && printf '%s\t%s\n' "$r" "$(basename "$r")"; done >"$TMP_DIR/rootchoices"; while IFS='\t' read -r r n; do set -- "$@" "$r" "$n"; done <"$TMP_DIR/rootchoices"; [ $# -ge 4 ] || { ui_msg Compare 'At least two rootfs instances are required.'; return; }; a=$(ui_menu 'First rootfs' 'Select first rootfs.' "$@") || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; b=$(ui_menu 'Second rootfs' 'Select second rootfs.' "$@") || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; fa=$TMP_DIR/pkgs-a; fb=$TMP_DIR/pkgs-b; chroot "$a" sh -c 'dpkg-query -W -f="${Package}\n" 2>/dev/null || apk info 2>/dev/null || pacman -Qq 2>/dev/null' | sort -u >"$fa"; chroot "$b" sh -c 'dpkg-query -W -f="${Package}\n" 2>/dev/null || apk info 2>/dev/null || pacman -Qq 2>/dev/null' | sort -u >"$fb"; ui_text 'Package comparison' "Only in $(basename "$a"):\n$(comm -23 "$fa" "$fb")\n\nOnly in $(basename "$b"):\n$(comm -13 "$fa" "$fb")"; }
