#!/bin/sh

rootfs_manager_details(){
  r=$(active_rootfs); f=$(rootfs_meta_file "$r"); rootfs_register "$r"; ui_text 'RootFS details' "Path: $r
Label: $(rootfs_meta_get "$r" label)
OS: $(aok_root_os "$r")
Architecture: $(aok_root_arch "$r")
Size: $(rootfs_human_size "$r")
Tags: $(rootfs_meta_get "$r" tags)
Description: $(rootfs_meta_get "$r" description)
Metadata: $f";
}
rootfs_manager_edit(){ r=$(active_rootfs); label=$(ui_input 'RootFS metadata' 'Display label' "$(rootfs_meta_get "$r" label)") || return; tags=$(ui_input 'RootFS metadata' 'Tags (comma separated)' "$(rootfs_meta_get "$r" tags)") || return; desc=$(ui_input 'RootFS metadata' 'Description' "$(rootfs_meta_get "$r" description)") || return; rootfs_set_meta "$r" label "$label"; rootfs_set_meta "$r" tags "$tags"; rootfs_set_meta "$r" description "$desc"; }
rootfs_manager_clone(){ r=$(active_rootfs); [ "$r" != / ] || { ui_msg RootFS 'Cloning the host root is blocked.'; return; }; dest=$(ui_input 'Clone RootFS' 'Destination directory' "${r}-clone") || return; [ ! -e "$dest" ] || { ui_msg Error 'Destination already exists.'; return; }; aok_confirm "Clone $r to $dest?" || return; if have rsync; then run_capture 'Clone RootFS' rsync -aH --numeric-ids "$r/" "$dest/"; else run_capture 'Clone RootFS' cp -a "$r" "$dest"; fi; [ -d "$dest" ] && rootfs_register "$dest"; }
rootfs_manager_archive(){ r=$(active_rootfs); name=$(aok_safe_name "$(root_label)"); out=$(ui_input 'Archive RootFS' 'Output tar.gz' "$AOK_SNAPSHOT_DIR/$name-$(date +%Y%m%d-%H%M%S).tar.gz") || return; aok_confirm "Create archive $out?" || return; run_capture 'Archive RootFS' tar -czf "$out" -C "$r" .; [ -f "$out" ] && { have sha256sum && sha256sum "$out" >"$out.sha256"; ui_msg Archive "$out"; }; }
rootfs_manager_manifest(){ r=$(active_rootfs); out="$ROOTFS_REPORT_DIR/$(rootfs_id "$r")-manifest-$(date +%Y%m%d-%H%M%S).txt"; rootfs_manifest "$r" "$out"; ui_text 'RootFS manifest' "$(cat "$out")"; }
rootfs_manager_compare(){ other=$(rootfs_select_registered) || return; r=$(active_rootfs); out="$ROOTFS_REPORT_DIR/diff-$(rootfs_id "$r")-$(rootfs_id "$other")-$(date +%Y%m%d-%H%M%S).txt"; { echo "RootFS A: $r"; echo "RootFS B: $other"; echo; echo '[disk usage]'; du -sh "$r" "$other" 2>/dev/null; echo; echo '[top-level differences]'; diff -qr "$r/etc" "$other/etc" 2>/dev/null | head -300; } >"$out"; ui_text 'RootFS comparison' "$(cat "$out")"; }
rootfs_manager_menu(){ while :; do c=$(ui_menu 'RootFS Manager' "Active: $(active_rootfs)" select 'Select or discover rootfs' details 'View details and statistics' metadata 'Edit label, tags and description' clone 'Clone active rootfs' archive 'Archive and checksum' manifest 'Generate inventory manifest' compare 'Compare with another rootfs') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in select) aok_select_root;; details) rootfs_manager_details;; metadata) rootfs_manager_edit;; clone) rootfs_manager_clone;; archive) rootfs_manager_archive;; manifest) rootfs_manager_manifest;; compare) rootfs_manager_compare;; esac; done; }

rootfs_health_report(){
  r=$(active_rootfs); out="$ROOTFS_REPORT_DIR/health-$(rootfs_id "$r")-$(date +%Y%m%d-%H%M%S).txt"; score=100; : >"$out"
  check(){ n=$1; shift; if "$@"; then printf '[OK] %s\n' "$n" >>"$out"; else printf '[FAIL] %s\n' "$n" >>"$out"; score=$((score-10)); fi; }
  check 'Root directory' test -d "$r"; check 'Shell' test -x "$r/bin/sh"; check 'os-release' test -r "$r/etc/os-release"; check 'passwd database' test -r "$r/etc/passwd"; check 'group database' test -r "$r/etc/group"; check 'DNS configuration' test -s "$r/etc/resolv.conf"; check 'Temporary directory' test -d "$r/tmp"; check 'Device mountpoint' test -d "$r/dev"; check 'Proc mountpoint' test -d "$r/proc"; check 'Package manager' sh -c "test -x '$r/usr/bin/apt-get' -o -x '$r/sbin/apk' -o -x '$r/usr/bin/pacman' -o -x '$r/usr/bin/dnf' -o -x '$r/usr/bin/xbps-install'"
  [ "$score" -lt 0 ] && score=0; { echo; echo "Health score: $score/100"; echo "RootFS: $r"; echo "OS: $(aok_root_os "$r")"; echo "Architecture: $(aok_root_arch "$r")"; echo; echo '[broken symlinks]'; find "$r" -xdev -type l ! -exec test -e {} \; -print 2>/dev/null | head -100; echo; echo '[world-writable files]'; find "$r/etc" -xdev -type f -perm -0002 -print 2>/dev/null | head -100; } >>"$out"; printf '%s' "$out"
}
rootfs_health_dashboard(){ out=$(rootfs_health_report); ui_text 'RootFS Health Dashboard' "$(cat "$out")"; }

repair_dns(){ r=$(active_rootfs); backup_file "$r/etc/resolv.conf"; mkdir -p "$r/etc"; printf 'nameserver 1.1.1.1\nnameserver 8.8.8.8\n' >"$r/etc/resolv.conf"; }
repair_runtime_dirs(){ r=$(active_rootfs); for d in dev dev/pts proc sys run tmp var/tmp var/lock; do mkdir -p "$r/$d"; done; chmod 1777 "$r/tmp" "$r/var/tmp" 2>/dev/null || true; }
repair_hostname(){ r=$(active_rootfs); h=$(ui_input Hostname 'Hostname for active rootfs' "$(cat "$r/etc/hostname" 2>/dev/null || echo ish-aok)") || return; printf '%s\n' "$h" >"$r/etc/hostname"; grep -q '127.0.1.1' "$r/etc/hosts" 2>/dev/null || printf '127.0.1.1 %s\n' "$h" >>"$r/etc/hosts"; }
repair_shells(){ r=$(active_rootfs); [ -x "$r/bin/sh" ] || { [ -x "$r/bin/bash" ] && ln -sf bash "$r/bin/sh"; [ -x "$r/bin/busybox" ] && ln -sf busybox "$r/bin/sh"; }; }
rootfs_repair_studio(){ while :; do c=$(ui_menu 'Repair Studio' "Active: $(active_rootfs)" auto 'Run safe automatic repairs' dns 'Repair resolv.conf' runtime 'Create runtime and mount directories' hostname 'Repair hostname and hosts' shell 'Repair /bin/sh link' packages 'Open package repair tools' permissions 'Open integrity and permission tools' health 'Run health report') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in auto) repair_runtime_dirs; repair_shells; [ -s "$(root_path /etc/resolv.conf)" ] || repair_dns; ui_msg Repair 'Safe repairs completed.';; dns) aok_confirm 'Replace resolv.conf with public DNS servers?' && repair_dns;; runtime) repair_runtime_dirs;; hostname) repair_hostname;; shell) repair_shells;; packages) aok_arch_packages_menu;; permissions) aok_advanced_tools_menu;; health) rootfs_health_dashboard;; esac; done; }

chroot_profile_run(){ p=$1; r=$(active_rootfs); [ "$r" != / ] || { ui_msg Chroot 'Select a non-host rootfs.'; return; }; repair_runtime_dirs; case $p in minimal) mounts='proc devpts';; readonly) mounts='proc dev devpts sys';; *) mounts='proc dev devpts sys run';; esac; for m in $mounts; do case $m in proc) aok_mountpoint "$r/proc" || as_root mount -t proc proc "$r/proc";; dev) aok_mountpoint "$r/dev" || as_root mount --rbind /dev "$r/dev";; devpts) aok_mountpoint "$r/dev/pts" || as_root mount -t devpts devpts "$r/dev/pts";; sys) [ -d /sys ] && { aok_mountpoint "$r/sys" || as_root mount --rbind /sys "$r/sys"; };; run) [ -d /run ] && { aok_mountpoint "$r/run" || as_root mount --bind /run "$r/run"; };; esac; done; [ "$p" = readonly ] && as_root mount -o remount,bind,ro "$r" 2>/dev/null || true; shell=/bin/sh; [ -x "$r/bin/bash" ] && shell=/bin/bash; as_root chroot "$r" "$shell"; }
chroot_studio_menu(){ while :; do c=$(ui_menu 'Chroot Studio' "Active: $(active_rootfs)" dev 'Development profile' build 'Build profile' debug 'Debug profile' minimal 'Minimal mounts' readonly 'Read-only profile' mounts 'Mount profile manager' preflight 'Run health and compatibility preflight' unmount 'Unmount active rootfs mounts') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in dev|build|debug|minimal|readonly) chroot_profile_run "$c";; mounts) mount_rootfs_profiles_menu 2>/dev/null || mount_manager_menu;; preflight) rootfs_health_dashboard;; unmount) for p in dev/pts dev sys proc run; do aok_mountpoint "$(active_rootfs)/$p" && as_root umount -l "$(active_rootfs)/$p" 2>/dev/null || true; done;; esac; done; }


rootfs_compatibility_report(){
  r=$(active_rootfs); out="$ROOTFS_REPORT_DIR/compatibility-$(rootfs_id "$r")-$(date +%Y%m%d-%H%M%S).txt"
  { echo "iSH-AOK compatibility report"; echo "RootFS: $r"; echo "OS: $(aok_root_os "$r")"; echo "Architecture: $(aok_root_arch "$r")"; echo; echo '[init]';
    if [ -x "$r/sbin/init" ]; then file "$r/sbin/init" 2>/dev/null; else echo 'FAIL: /sbin/init missing'; fi
    [ -d "$r/etc/init.d" ] && echo 'OK: SysV init scripts present' || echo 'WARN: /etc/init.d missing'
    [ -d "$r/etc/runlevels" ] && echo 'OK: OpenRC runlevels present' || true
    [ -d "$r/run/systemd/system" -o -d "$r/etc/systemd" ] && echo 'WARN: systemd assumptions detected' || echo 'OK: no obvious systemd runtime dependency'
    echo; echo '[architecture and ELF]'; for b in "$r/bin/sh" "$r/sbin/init" "$r/usr/bin/env"; do [ -e "$b" ] && file "$b" 2>/dev/null; done
    echo; echo '[dynamic interpreters]'; find "$r/bin" "$r/sbin" "$r/usr/bin" -type f -perm -0100 2>/dev/null | head -100 | while IFS= read -r b; do readelf -l "$b" 2>/dev/null | sed -n "s#.*interpreter: \(.*\)]#$(printf '%s' "$b" | sed "s#^$r##"): \1#p"; done
    echo; echo '[kernel and filesystem assumptions]'; grep -R -l -E 'systemctl|/run/systemd|cgroup|udevadm|mount -t (cgroup|overlay)|modprobe' "$r/etc" "$r/usr/lib" 2>/dev/null | head -100
    echo; echo '[QEMU emulators]'; command -v qemu-aarch64-static 2>/dev/null || true; command -v qemu-x86_64-static 2>/dev/null || true; command -v qemu-riscv64-static 2>/dev/null || true
  } >"$out"; printf '%s' "$out"
}
rootfs_compatibility_studio(){ while :; do c=$(ui_menu 'Compatibility Studio' "Active: $(active_rootfs)" report 'Generate iSH-AOK compatibility report' existing 'Open advanced preflight tools' init 'Open init conversion tools' arch 'Open architecture repair tools') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in report) out=$(rootfs_compatibility_report); ui_text Compatibility "$(cat "$out")";; existing) aok_advanced_tools_menu;; init) aok_repos_init_ssh_menu;; arch) aok_arch_packages_menu;; esac; done; }

rootfs_export_archive(){ r=$(active_rootfs); fmt=$(ui_menu 'Export RootFS' 'Choose archive format.' tgz 'tar.gz' txz 'tar.xz' tar 'uncompressed tar') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; base="$AOK_SNAPSHOT_DIR/$(aok_safe_name "$(root_label)")-$(date +%Y%m%d-%H%M%S)"; case $fmt in tgz) out=$base.tar.gz; cmd='tar -czf';; txz) out=$base.tar.xz; cmd='tar -cJf';; tar) out=$base.tar; cmd='tar -cf';; esac; aok_confirm "Export active rootfs to $out?" || return; sh -c "$cmd \"$out\" -C \"$r\" ."; rc=$?; [ $rc -eq 0 ] && { have sha256sum && sha256sum "$out" >"$out.sha256"; ui_msg Export "$out"; }; return $rc; }
rootfs_import_archive(){ src=$(ui_input 'Import RootFS' 'Archive path') || return; [ -f "$src" ] || { ui_msg Error 'Archive not found.'; return; }; dest=$(ui_input 'Import RootFS' 'Destination directory' "/root/$(basename "$src" | sed 's/\.tar.*//')") || return; [ ! -e "$dest" ] || { ui_msg Error 'Destination exists.'; return; }; mkdir -p "$dest" || return; case $src in *.tar.gz|*.tgz) tar -xzf "$src" -C "$dest";; *.tar.xz|*.txz) tar -xJf "$src" -C "$dest";; *.tar) tar -xf "$src" -C "$dest";; *) ui_msg Error 'Unsupported archive format.'; return 1;; esac; rootfs_register "$dest"; set_active_rootfs "$dest"; ui_msg Import "Imported and selected:\n$dest"; }
rootfs_import_export_studio(){ while :; do c=$(ui_menu 'Import / Export Studio' "Active: $(active_rootfs)" import 'Import tar archive' export 'Export active rootfs' verify 'Verify SHA-256 checksum' archives 'Open existing archive tools') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in import) rootfs_import_archive;; export) rootfs_export_archive;; verify) f=$(ui_input Verify 'Path to .sha256 file') || continue; [ -f "$f" ] && (cd "$(dirname "$f")" && sha256sum -c "$(basename "$f")") 2>&1 | ui_text Verify "$(cat)";; archives) aok_filesystems_menu;; esac; done; }

rootfs_optimization_report(){ r=$(active_rootfs); out="$ROOTFS_REPORT_DIR/optimization-$(rootfs_id "$r")-$(date +%Y%m%d-%H%M%S).txt"; { echo "RootFS optimization estimate"; echo "RootFS: $r"; echo "Current size: $(rootfs_human_size "$r")"; echo; for d in var/cache var/log tmp var/tmp usr/share/doc usr/share/man usr/share/locale; do [ -e "$r/$d" ] && du -sh "$r/$d" 2>/dev/null; done; echo; echo '[largest files]'; find "$r" -xdev -type f -size +5M -exec du -h {} \; 2>/dev/null | sort -hr | head -50; } >"$out"; printf '%s' "$out"; }
rootfs_safe_cleanup(){ r=$(active_rootfs); aok_confirm 'Remove package caches, temporary files, and rotated logs from the active rootfs?' || return; rm -rf "$r/var/cache/apt/archives/"*.deb "$r/var/cache/apk/"* "$r/var/cache/pacman/pkg/"* "$r/tmp/"* "$r/var/tmp/"* 2>/dev/null || true; find "$r/var/log" -type f \( -name '*.gz' -o -name '*.old' -o -name '*.[0-9]' \) -delete 2>/dev/null || true; ui_msg Optimization 'Safe cleanup completed.'; }
rootfs_optimization_studio(){ while :; do c=$(ui_menu 'Optimization Studio' "Active: $(active_rootfs)" report 'Estimate space usage and savings' cleanup 'Safe cache and temporary-file cleanup' existing 'Open advanced optimization tools') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in report) out=$(rootfs_optimization_report); ui_text Optimization "$(cat "$out")";; cleanup) rootfs_safe_cleanup;; existing) aok_optimize_sync_menu;; esac; done; }

rootfs_reports_studio(){ while :; do c=$(ui_menu 'Reports Studio' "Active: $(active_rootfs)" health 'Health report' compatibility 'Compatibility report' manifest 'Package and service manifest' optimization 'Optimization report' environment 'AOK environment report' browse 'List generated reports') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in health) out=$(rootfs_health_report); ui_text Health "$(cat "$out")";; compatibility) out=$(rootfs_compatibility_report); ui_text Compatibility "$(cat "$out")";; manifest) rootfs_manager_manifest;; optimization) out=$(rootfs_optimization_report); ui_text Optimization "$(cat "$out")";; environment) aok_environment_report;; browse) ui_text Reports "$(find "$ROOTFS_REPORT_DIR" -type f -maxdepth 1 2>/dev/null | sort | tail -100)";; esac; done; }

# Expanded studio hub. Existing specialist modules are reused where they are already mature.
aok_v7_studios_menu(){ while :; do c=$(ui_menu 'iSH-AOK Studios' "Active: $(active_rootfs)" manager 'RootFS Manager' health 'Health Dashboard' repair 'Repair Studio' chroot 'Chroot Studio' build 'Build Studio' package 'Package Studio' snapshots 'Snapshot Studio' compatibility 'Compatibility Studio' transfer 'Import / Export Studio' optimize 'Optimization Studio' reports 'Reports Studio') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in manager) rootfs_manager_menu;; health) rootfs_health_dashboard;; repair) rootfs_repair_studio;; chroot) chroot_studio_menu;; build) aok_builder_studio;; package) package_center_v6;; snapshots) aok_snapshots_menu;; compatibility) rootfs_compatibility_studio;; transfer) rootfs_import_export_studio;; optimize) rootfs_optimization_studio;; reports) rootfs_reports_studio;; esac; done; }
