#!/bin/sh
aok_snapshot_create(){ r=$(active_rootfs); [ "$r" != / ] || { ui_msg Snapshot 'Select a non-host rootfs for full snapshots.'; return; }; label=$(ui_input Snapshot 'Label:' manual) || return; name="$(aok_safe_name "$(root_label)-$label-$(date +%Y%m%d-%H%M%S)")"; out="$AOK_SNAPSHOT_DIR/$name.tar.gz"; run_capture Snapshot tar -czf "$out" -C "$(dirname "$r")" "$(basename "$r")"; }
aok_snapshot_config(){ o=$(aok_backup_root_config) && ui_msg Snapshot "$o"; }
aok_snapshot_list(){ ls -lh "$AOK_SNAPSHOT_DIR" >"$REPORT_DIR/aok-snapshots.txt" 2>&1; ui_text Snapshots "$(cat "$REPORT_DIR/aok-snapshots.txt")"; }
aok_snapshot_restore(){ a=$(ui_input Restore 'Snapshot archive:' '') || return; d=$(ui_input Restore 'Destination parent directory:' '/AOK/roots') || return; [ -f "$a" ] || return; aok_confirm "Restore $a under $d? Existing files may be overwritten." && run_capture Restore as_root tar -xzf "$a" -C "$d"; }
aok_snapshot_verify(){ a=$(ui_input Verify 'Snapshot archive:' '') || return; run_capture Verify tar -tzf "$a"; }
aok_snapshot_delete(){ a=$(ui_input Delete 'Snapshot archive:' '') || return; case $a in "$AOK_SNAPSHOT_DIR"/*) aok_confirm "Delete $a?" && rm -f "$a";; *) ui_msg Safety 'Snapshot must be under the AOK snapshot directory.';; esac; }
aok_fs_diagnostics(){ r=$(active_rootfs); out=$(aok_report_file filesystem); { echo "Root: $r"; df -h "$r"; echo; find "$r" -xdev -type l ! -exec test -e {} \; -print 2>/dev/null | head -n 300; echo; find "$r" -xdev -type f -perm -0002 2>/dev/null | head -n 300; } >"$out"; ui_text Filesystem "$(cat "$out")"; }
aok_full_diagnostics(){ out=$(aok_report_file full-aok); { echo 'AOK FULL DIAGNOSTIC'; date; echo; aok_environment_report >/dev/null 2>&1 || true; cat "$REPORT_DIR"/aok-environment-*.txt 2>/dev/null | tail -n 400; echo; echo 'ACTIVE ROOT'; echo "$(active_rootfs)"; echo; echo 'MOUNTS'; grep " $(active_rootfs)" /proc/mounts; echo; echo 'STATE'; aok_state_files | while read f; do echo "$f: $(head -n1 "$f")"; done; echo; echo 'PACKAGE MANAGER'; aok_pkg_manager_detect; echo; echo 'REPOSITORIES'; aok_repo_files; echo; echo 'INIT'; ls -l "$(active_rootfs)/sbin/init" 2>&1; echo; echo 'ARCH'; aok_root_arch "$(active_rootfs)"; echo; echo 'STORAGE'; df -h "$(active_rootfs)"; echo; echo 'PROCESSES'; ps aux 2>/dev/null | head -n 100; } >"$out"; ui_text Diagnostics "$(cat "$out")"; }
aok_support_archive(){ d="$TMP_DIR/support"; mkdir -p "$d"; aok_full_diagnostics >/dev/null 2>&1 || true; cp "$REPORT_DIR"/*aok* "$d"/ 2>/dev/null || true; sed -i 's/\(password\|token\|secret\)[^ ]*/\1=REDACTED/Ig' "$d"/* 2>/dev/null || true; o="$CURRENT_HOME/aok-support-$(date +%Y%m%d-%H%M%S).tar.gz"; tar -czf "$o" -C "$d" .; ui_msg Support "$o"; }
aok_source_tree(){ for d in /opt/AOK /AOK; do [ -d "$d" ] && find "$d" -maxdepth 3 -type f | head -n 500; done >"$REPORT_DIR/aok-source-tree.txt"; ui_text Source "$(cat "$REPORT_DIR/aok-source-tree.txt")"; }
aok_source_search(){ q=$(ui_input Search 'Pattern:' systemctl) || return; run_capture Search grep -RIn -- "$q" /opt/AOK /AOK; }
aok_git_init(){ d=$(ui_input Git 'AOK source directory:' /opt/AOK) || return; [ -d "$d" ] || return; (cd "$d" && git init && git add -A && git commit -m 'Baseline AOK source') >"$TMP_DIR/git" 2>&1; ui_text Git "$(cat "$TMP_DIR/git")"; }
aok_shell_audit(){ d=$(ui_input Audit 'AOK source directory:' /opt/AOK) || return; out=$(aok_report_file shell-audit); { find "$d" -type f -name '*.sh' -exec sh -n {} \; 2>&1; grep -RInE 'systemctl|journalctl|/run/systemd|uname -m.*=' "$d" 2>/dev/null | head -n 500; } >"$out"; have shellcheck && find "$d" -type f -name '*.sh' -exec shellcheck -s sh {} + >>"$out" 2>&1 || true; ui_text Audit "$(cat "$out")"; }
aok_snapshots_menu(){ while :; do c=$(ui_menu 'Snapshots & rollback' "Directory: $AOK_SNAPSHOT_DIR" full 'Create full rootfs snapshot' config 'Create configuration snapshot' list 'List snapshots' verify 'Verify snapshot' restore 'Restore snapshot' delete 'Delete snapshot' compare 'Compare snapshot metadata' retention 'Configure retention policy') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in full) aok_snapshot_create;; config) aok_snapshot_config;; list) aok_snapshot_list;; verify) aok_snapshot_verify;; restore) aok_snapshot_restore;; delete) aok_snapshot_delete;; compare) aok_snapshot_list;; retention) edit_file "$AOK_STATE_DIR/snapshot-retention.conf";; esac; done; }
aok_diagnostics_menu(){ while :; do c=$(ui_menu 'AOK diagnostics & recommended fixes' "Active: $(active_rootfs)" full 'Full AOK diagnostic report' environment 'Environment/capability report' mounts 'Mount and chroot diagnostics' state 'Build-state diagnostics' package 'Package-manager diagnostics' repos 'Repository diagnostics' ssh 'SSH diagnostics' init 'Init-system diagnostics' arch 'Architecture diagnostics' filesystem 'Filesystem and permissions' libraries 'Dynamic-linker/missing libraries' services 'Service/process diagnostics' support 'Create redacted support archive' fixes 'Show recommended fixes') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in full) aok_full_diagnostics;; environment) aok_environment_report;; mounts) aok_vfs_check;; state) aok_state_inspect;; package) aok_pkg_partial; aok_pkg_inventory;; repos) aok_repo_test;; ssh) r=$(active_rootfs); run_capture SSH as_root chroot "$r" /usr/sbin/sshd -T;; init) aok_init_detect;; arch) aok_arch_scan;; filesystem) aok_fs_diagnostics;; libraries) aok_missing_libraries;; services) aok_chroot_processes;; support) aok_support_archive;; fixes) aok_recommended_fixes;; esac; done; }
aok_recommended_fixes(){ r=$(active_rootfs); text=''; [ "$r" != / ] && ! aok_mountpoint "$r/proc" && text="$text\n- Mount /proc before chroot operations."; [ -e "$r/var/lib/dpkg/lock" ] && text="$text\n- Review stale dpkg lock."; [ ! -e "$r/etc/resolv.conf" ] && text="$text\n- Copy /etc/resolv.conf into rootfs."; [ -x "$r/usr/sbin/sshd" ] && [ ! -f "$r/etc/ssh/ssh_host_ed25519_key" ] && text="$text\n- Generate SSH host keys."; [ -z "$text" ] && text='No obvious high-confidence fixes detected.'; ui_text Fixes "$text"; }
aok_developer_menu(){ while :; do c=$(ui_menu 'AOK developer tools' 'Source inspection, patching and compatibility audits.' tree 'Browse AOK source tree' search 'Search AOK source' edit 'Edit selected AOK script' audit 'POSIX/systemd/architecture audit' gitinit 'Initialize Git baseline' status 'Show Git status/diff' patch 'Create patch bundle' apply 'Apply patch file' revert 'Revert with Git' logs 'Inspect build/setup logs' trace 'Run script with shell tracing') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in tree) aok_source_tree;; search) aok_source_search;; edit) f=$(ui_input Edit 'AOK script path:' /opt/AOK/build_fs) || continue; edit_file "$f";; audit) aok_shell_audit;; gitinit) aok_git_init;; status) d=$(ui_input Git 'AOK source directory:' /opt/AOK) || continue; run_capture Git sh -c "cd '$d' && git status --short && git diff";; patch) d=$(ui_input Git 'AOK source directory:' /opt/AOK) || continue; o="$AOK_PATCH_DIR/aok-$(date +%Y%m%d-%H%M%S).patch"; (cd "$d" && git diff >"$o"); ui_msg Patch "$o";; apply) p=$(ui_input Patch 'Patch file:' '') || continue; d=$(ui_input Patch 'AOK source directory:' /opt/AOK) || continue; run_capture Patch sh -c "cd '$d' && patch -p1 < '$p'";; revert) d=$(ui_input Git 'AOK source directory:' /opt/AOK) || continue; aok_confirm 'Discard all Git-tracked changes?' && (cd "$d" && git reset --hard);; logs) aok_build_logs;; trace) s=$(ui_input Trace 'Script path:' /opt/AOK/build_fs) || continue; run_capture Trace sh -x "$s";; esac; done; }
