#!/bin/sh
cfg_on(){ f=$1; p=$2; grep -Eq "^[[:space:]]*$p([[:space:]]|$)" "$f" 2>/dev/null && printf on || printf off; }
vim_on(){ f=$1; p=$2; grep -Eq "^[[:space:]]*set[[:space:]]+([^\"]*[[:space:]])?$p([[:space:]=]|$)" "$f" 2>/dev/null && ! grep -Eq "^[[:space:]]*set[[:space:]]+no$p([[:space:]]|$)" "$f" 2>/dev/null && printf on || printf off; }
selected_has(){ printf '%s\n' "$1" | grep -Fxq "$2"; }
config_target_menu(){ title=$1; file=$2; wizard=$3; template=$4; while :; do state=missing; [ -s "$file" ] && state=present; c=$(ui_menu "$title" "$file ($state)" wizard 'Configure options in TUI' edit 'Open raw configuration' defaults 'Install recommended defaults' view 'View current file' backup 'Create backup now' remove 'Remove tool-managed option block') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in wizard) "$wizard" "$file";; edit) [ -e "$file" ] || ensure_template "$template" "$file"; edit_file "$file";; defaults) if ui_yesno "$title" "Replace $file with the project defaults? A backup will be created."; then cp "$ISH_AOK_CONFIG_ROOT/templates/$template" "$TMP_DIR/default" && write_file "$file" 644 "$(cat "$TMP_DIR/default")"; fi;; view) [ -f "$file" ] && ui_text "$title" "$(cat "$file")" || ui_msg "$title" 'File does not exist.';; backup) backup_file "$file"; ui_msg Backup "Backup stored under $BACKUP_DIR";; remove) remove_managed_block "$file" "${template}-options";; esac; done; }
remove_managed_block(){ f=$1; name=$2; [ -f "$f" ] || return; b="# >>> ish-aok-config: $name >>>"; e="# <<< ish-aok-config: $name <<<"; awk -v b="$b" -v e="$e" '$0==b{s=1;next}$0==e{s=0;next}!s{print}' "$f" >"$TMP_DIR/unmanaged" && write_file "$f" 644 "$(cat "$TMP_DIR/unmanaged")"; }

nano_wizard(){ f=$1; [ -e "$f" ] || write_file "$f" 644 ''; opts=$(ui_checklist 'Nano options' 'Space toggles options. Existing settings are preselected.' \
 linenumbers 'Line numbers' "$(cfg_on "$f" 'set[[:space:]]+linenumbers')" \
 mouse 'Mouse support' "$(cfg_on "$f" 'set[[:space:]]+mouse')" \
 softwrap 'Soft-wrap long lines' "$(cfg_on "$f" 'set[[:space:]]+softwrap')" \
 atblanks 'Wrap at whitespace' "$(cfg_on "$f" 'set[[:space:]]+atblanks')" \
 breaklonglines 'Hard-wrap long lines' "$(cfg_on "$f" 'set[[:space:]]+breaklonglines')" \
 tabstospaces 'Convert tabs to spaces' "$(cfg_on "$f" 'set[[:space:]]+tabstospaces')" \
 autoindent 'Automatic indentation' "$(cfg_on "$f" 'set[[:space:]]+autoindent')" \
 smarthome 'Smart Home key' "$(cfg_on "$f" 'set[[:space:]]+smarthome')" \
 constantshow 'Always show cursor position' "$(cfg_on "$f" 'set[[:space:]]+constantshow')" \
 minibar 'Compact status bar' "$(cfg_on "$f" 'set[[:space:]]+minibar')" \
 stateflags 'Show state flags' "$(cfg_on "$f" 'set[[:space:]]+stateflags')" \
 indicator 'Position indicator' "$(cfg_on "$f" 'set[[:space:]]+indicator')" \
 zap 'Backspace/Delete erase selection' "$(cfg_on "$f" 'set[[:space:]]+zap')" \
 quickblank 'Quick status-bar clearing' "$(cfg_on "$f" 'set[[:space:]]+quickblank')" \
 nohelp 'Hide help lines' "$(cfg_on "$f" 'set[[:space:]]+nohelp')" \
 nowrap 'Disable automatic hard wrapping' "$(cfg_on "$f" 'set[[:space:]]+nowrap')" \
 backup 'Create backup files' "$(cfg_on "$f" 'set[[:space:]]+backup')" \
 locking 'Use lock files' "$(cfg_on "$f" 'set[[:space:]]+locking')" \
 positionlog 'Remember cursor position' "$(cfg_on "$f" 'set[[:space:]]+positionlog')" \
 historylog 'Remember search history' "$(cfg_on "$f" 'set[[:space:]]+historylog')" \
 casesensitive 'Case-sensitive search' "$(cfg_on "$f" 'set[[:space:]]+casesensitive')" \
 regexp 'Regular-expression search' "$(cfg_on "$f" 'set[[:space:]]+regexp')" \
 unix 'Save in Unix format' "$(cfg_on "$f" 'set[[:space:]]+unix')" \
 trimblanks 'Trim trailing whitespace' "$(cfg_on "$f" 'set[[:space:]]+trimblanks')" \
 wordbounds 'More accurate word boundaries' "$(cfg_on "$f" 'set[[:space:]]+wordbounds')" \
 boldtext 'Use bold instead of reverse video' "$(cfg_on "$f" 'set[[:space:]]+boldtext')" \
 titlecolor 'Custom title color' "$(cfg_on "$f" 'set[[:space:]]+titlecolor')" \
 syntax 'Load system syntax definitions' "$(cfg_on "$f" 'include[[:space:]]+.*nano')") || return
 tab=$(ui_input Nano 'Tab width (1-16):' "$(sed -n 's/^[[:space:]]*set[[:space:]]\+tabsize[[:space:]]\+//p' "$f" | tail -1)") || return; [ -n "$tab" ] || tab=4
 fill=$(ui_input Nano 'Hard-wrap column (0 disables custom fill):' "$(sed -n 's/^[[:space:]]*set[[:space:]]\+fill[[:space:]]\+//p' "$f" | tail -1)") || return; [ -n "$fill" ] || fill=0
 body="# Options selected through the Nano TUI\nset tabsize $tab"
 for x in linenumbers mouse softwrap atblanks breaklonglines tabstospaces autoindent smarthome constantshow minibar stateflags indicator zap quickblank nohelp nowrap backup locking positionlog historylog casesensitive regexp unix trimblanks wordbounds boldtext; do selected_has "$opts" "$x" && body="$body\nset $x"; done
 [ "$fill" != 0 ] && body="$body\nset fill $fill"
 selected_has "$opts" titlecolor && body="$body\nset titlecolor brightwhite,blue\nset statuscolor brightwhite,green\nset keycolor cyan\nset functioncolor green"
 selected_has "$opts" syntax && body="$body\ninclude \"/usr/share/nano/*.nanorc\"\ninclude \"/usr/share/nano/extra/*.nanorc\""
 replace_block "$f" nanorc-options "$body"; ui_msg Nano 'Nano options saved.'; }

vim_wizard(){ f=$1; [ -e "$f" ] || write_file "$f" 644 ''; opts=$(ui_checklist 'Vim options' 'Select Vim behavior. Existing settings are preselected.' \
 number 'Absolute line numbers' "$(vim_on "$f" number)" relativenumber 'Relative line numbers' "$(vim_on "$f" relativenumber)" cursorline 'Highlight current line' "$(vim_on "$f" cursorline)" cursorcolumn 'Highlight current column' "$(vim_on "$f" cursorcolumn)" ruler 'Show cursor position' "$(vim_on "$f" ruler)" showcmd 'Show partial commands' "$(vim_on "$f" showcmd)" showmode 'Show current mode' "$(vim_on "$f" showmode)" wildmenu 'Command completion menu' "$(vim_on "$f" wildmenu)" laststatus 'Always show status line' "$(vim_on "$f" laststatus)" \
 syntax 'Enable syntax highlighting' "$(cfg_on "$f" 'syntax[[:space:]]+on')" filetype 'Filetype plugins and indent' "$(cfg_on "$f" 'filetype[[:space:]]+plugin')" \
 expandtab 'Spaces instead of tabs' "$(vim_on "$f" expandtab)" autoindent 'Auto indent' "$(vim_on "$f" autoindent)" smartindent 'Smart indent' "$(vim_on "$f" smartindent)" cindent 'C-style indent' "$(vim_on "$f" cindent)" smarttab 'Smart tabs' "$(vim_on "$f" smarttab)" \
 ignorecase 'Ignore case in search' "$(vim_on "$f" ignorecase)" smartcase 'Case-sensitive when uppercase used' "$(vim_on "$f" smartcase)" incsearch 'Incremental search' "$(vim_on "$f" incsearch)" hlsearch 'Highlight matches' "$(vim_on "$f" hlsearch)" wrapscan 'Wrap searches' "$(vim_on "$f" wrapscan)" \
 mouse 'Mouse in all modes' "$(cfg_on "$f" 'set[[:space:]]+mouse=a')" clipboard 'Use unnamed clipboard' "$(cfg_on "$f" 'set[[:space:]]+clipboard=unnamed')" hidden 'Allow hidden modified buffers' "$(vim_on "$f" hidden)" confirm 'Confirm destructive actions' "$(vim_on "$f" confirm)" autoread 'Auto-read changed files' "$(vim_on "$f" autoread)" \
 backup 'Enable backups' "$(vim_on "$f" backup)" writebackup 'Backup while writing' "$(vim_on "$f" writebackup)" swapfile 'Enable swap files' "$(vim_on "$f" swapfile)" undofile 'Persistent undo' "$(vim_on "$f" undofile)" \
 splitright 'Vertical splits open right' "$(vim_on "$f" splitright)" splitbelow 'Horizontal splits open below' "$(vim_on "$f" splitbelow)" scrolloff 'Keep context around cursor' "$(cfg_on "$f" 'set[[:space:]]+scrolloff=')" colorcolumn 'Show preferred line length' "$(cfg_on "$f" 'set[[:space:]]+colorcolumn=')" list 'Show whitespace characters' "$(vim_on "$f" list)" spell 'Spell checking' "$(vim_on "$f" spell)" \
 modeline 'Allow modelines' "$(vim_on "$f" modeline)" secure 'Secure local commands' "$(vim_on "$f" secure)") || return
 tab=$(ui_input Vim 'Tab/indent width:' "$(sed -n 's/^[[:space:]]*set[[:space:]].*tabstop=\([0-9][0-9]*\).*/\1/p' "$f" | tail -1)") || return; [ -n "$tab" ] || tab=4
 theme=$(ui_input Vim 'Colorscheme (blank leaves default):' "$(sed -n 's/^[[:space:]]*colorscheme[[:space:]]\+//p' "$f" | tail -1)") || return
 body='" Options selected through the Vim TUI\nset nocompatible'
 for x in number relativenumber cursorline cursorcolumn ruler showcmd showmode wildmenu expandtab autoindent smartindent cindent smarttab ignorecase smartcase incsearch hlsearch wrapscan hidden confirm autoread backup writebackup swapfile undofile splitright splitbelow list spell modeline secure; do selected_has "$opts" "$x" && body="$body\nset $x" || body="$body\nset no$x"; done
 selected_has "$opts" laststatus && body="$body\nset laststatus=2"
 selected_has "$opts" syntax && body="$body\nsyntax enable"
 selected_has "$opts" filetype && body="$body\nfiletype plugin indent on"
 selected_has "$opts" mouse && body="$body\nset mouse=a" || body="$body\nset mouse="
 selected_has "$opts" clipboard && body="$body\nset clipboard=unnamed"
 selected_has "$opts" scrolloff && body="$body\nset scrolloff=5"
 selected_has "$opts" colorcolumn && body="$body\nset colorcolumn=80"
 body="$body\nset tabstop=$tab\nset shiftwidth=$tab\nset softtabstop=$tab\nset backspace=indent,eol,start\nset encoding=utf-8"
 selected_has "$opts" list && body="$body\nset listchars=tab:>-,trail:·,extends:>,precedes:<"
 [ -n "$theme" ] && body="$body\ncolorscheme $theme"
 replace_block "$f" vimrc-options "$body"; have vim && vim -Nu "$f" -n -es +'qall' >/dev/null 2>"$TMP_DIR/vimcheck" || true; [ -s "$TMP_DIR/vimcheck" ] && ui_text 'Vim validation warnings' "$(cat "$TMP_DIR/vimcheck")" || ui_msg Vim 'Vim options saved.'; }

bash_wizard(){ f=$1; hist=$(ui_input Bash 'History size:' 5000) || return; prompt=$(ui_input Bash 'PS1 prompt:' '\u@\h:\w\$ ') || return; opts=$(ui_checklist Bash 'Select Bash options.' histappend 'Append history' on checkwinsize 'Update terminal dimensions' on cmdhist 'Combine multiline history' on lithist 'Preserve embedded newlines' off globstar 'Recursive ** glob' off autocd 'Directory names execute cd' off nocaseglob 'Case-insensitive globbing' off direxpand 'Expand directories during completion' on cdspell 'Correct minor cd spelling errors' off checkjobs 'Warn about running jobs on exit' on sourcealiases 'Load ~/.aliases' on completion 'Load bash-completion' on) || return; body="# Bash options selected through TUI\nHISTCONTROL=ignoreboth:erasedups\nHISTSIZE=$hist\nHISTFILESIZE=$hist\nPS1='$prompt'"; for x in histappend checkwinsize cmdhist lithist globstar autocd nocaseglob direxpand cdspell checkjobs; do selected_has "$opts" "$x" && body="$body\nshopt -s $x" || body="$body\nshopt -u $x"; done; selected_has "$opts" sourcealiases && body="$body\n[ -f \"\$HOME/.aliases\" ] && . \"\$HOME/.aliases\""; selected_has "$opts" completion && body="$body\n[ -r /etc/bash_completion ] && . /etc/bash_completion\n[ -r /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion"; replace_block "$f" bashrc-options "$body"; }

zsh_wizard(){ f=$1; size=$(ui_input Zsh 'History size:' 5000) || return; opts=$(ui_checklist Zsh 'Select Zsh options.' appendhistory 'Append history' on sharehistory 'Share history across shells' on ignoredups 'Ignore duplicate history' on autocd 'Automatic cd' on correct 'Command correction' off extendedglob 'Extended glob syntax' on nomatch 'Error on unmatched glob' off interactivecomments 'Comments at prompt' on promptsubst 'Prompt substitution' on completion 'Initialize completion' on aliases 'Load ~/.aliases' on) || return; body="# Zsh options selected through TUI\nHISTFILE=\$HOME/.zsh_history\nHISTSIZE=$size\nSAVEHIST=$size"; selected_has "$opts" appendhistory && body="$body\nsetopt APPEND_HISTORY"; selected_has "$opts" sharehistory && body="$body\nsetopt SHARE_HISTORY"; selected_has "$opts" ignoredups && body="$body\nsetopt HIST_IGNORE_ALL_DUPS"; selected_has "$opts" autocd && body="$body\nsetopt AUTO_CD"; selected_has "$opts" correct && body="$body\nsetopt CORRECT"; selected_has "$opts" extendedglob && body="$body\nsetopt EXTENDED_GLOB"; selected_has "$opts" nomatch || body="$body\nunsetopt NOMATCH"; selected_has "$opts" interactivecomments && body="$body\nsetopt INTERACTIVE_COMMENTS"; selected_has "$opts" promptsubst && body="$body\nsetopt PROMPT_SUBST"; selected_has "$opts" completion && body="$body\nautoload -Uz compinit && compinit"; selected_has "$opts" aliases && body="$body\n[ -f \"\$HOME/.aliases\" ] && source \"\$HOME/.aliases\""; replace_block "$f" zshrc-options "$body"; }

inputrc_wizard(){ f=$1; mode=$(ui_radiolist Inputrc 'Editing mode' emacs Emacs on vi Vi off) || return; opts=$(ui_checklist Inputrc 'Readline options.' ignorecase 'Case-insensitive completion' on ambiguous 'Show choices immediately' on visible 'Visible bell' off colored 'Colored completion prefix' on markdirs 'Mark directories with slash' on symlinks 'Complete symlinked directory names' on history 'Arrow-key history prefix search' on) || return; body="# Readline options selected through TUI\nset editing-mode $mode"; selected_has "$opts" ignorecase && body="$body\nset completion-ignore-case on"; selected_has "$opts" ambiguous && body="$body\nset show-all-if-ambiguous on"; selected_has "$opts" visible && body="$body\nset bell-style visible" || body="$body\nset bell-style none"; selected_has "$opts" colored && body="$body\nset colored-completion-prefix on"; selected_has "$opts" markdirs && body="$body\nset mark-directories on"; selected_has "$opts" symlinks && body="$body\nset mark-symlinked-directories on"; selected_has "$opts" history && body="$body\n\"\\e[A\": history-search-backward\n\"\\e[B\": history-search-forward"; replace_block "$f" inputrc-options "$body"; }

git_wizard(){ f=$1; name=$(ui_input Git 'User name:' "$(git config --global user.name 2>/dev/null)") || return; email=$(ui_input Git 'User email:' "$(git config --global user.email 2>/dev/null)") || return; editor=$(ui_input Git 'Editor command:' "$(git config --global core.editor 2>/dev/null || echo nano)") || return; branch=$(ui_input Git 'Default branch:' "$(git config --global init.defaultBranch 2>/dev/null || echo main)") || return; pull=$(ui_radiolist Git 'git pull strategy' merge Merge on rebase Rebase off ffonly 'Fast-forward only' off) || return; body="[user]\n    name = $name\n    email = $email\n[core]\n    editor = $editor\n[init]\n    defaultBranch = $branch\n[color]\n    ui = auto\n[fetch]\n    prune = true"; case $pull in merge) body="$body\n[pull]\n    rebase = false";; rebase) body="$body\n[pull]\n    rebase = true";; ffonly) body="$body\n[pull]\n    ff = only";; esac; replace_block "$f" gitconfig-options "$body"; }

tmux_wizard(){ f=$1; prefix=$(ui_radiolist Tmux 'Prefix key' C-b 'Ctrl-b (default)' on C-a Ctrl-a off) || return; hist=$(ui_input Tmux 'History lines:' 20000) || return; opts=$(ui_checklist Tmux 'Tmux options.' mouse Mouse on baseone 'Windows/panes start at 1' on renumber 'Renumber windows after close' on vi 'Vi copy mode' off status 'Show status bar' on activity 'Monitor activity' off titles 'Set terminal title' on escape 'Reduce escape delay' on) || return; body="# Tmux options selected through TUI\nset -g history-limit $hist"; [ "$prefix" = C-a ] && body="$body\nunbind C-b\nset -g prefix C-a\nbind C-a send-prefix"; selected_has "$opts" mouse && body="$body\nset -g mouse on" || body="$body\nset -g mouse off"; selected_has "$opts" baseone && body="$body\nset -g base-index 1\nsetw -g pane-base-index 1"; selected_has "$opts" renumber && body="$body\nset -g renumber-windows on"; selected_has "$opts" vi && body="$body\nsetw -g mode-keys vi"; selected_has "$opts" status || body="$body\nset -g status off"; selected_has "$opts" activity && body="$body\nsetw -g monitor-activity on\nset -g visual-activity on"; selected_has "$opts" titles && body="$body\nset -g set-titles on"; selected_has "$opts" escape && body="$body\nset -sg escape-time 10"; replace_block "$f" tmux-options "$body"; have tmux && tmux -f "$f" start-server \; kill-server >/dev/null 2>"$TMP_DIR/tmuxcheck" || true; }

ssh_client_wizard(){ f=$1; host=$(ui_input 'SSH client' 'Host pattern:' '*') || return; interval=$(ui_input 'SSH client' 'ServerAliveInterval seconds:' 60) || return; count=$(ui_input 'SSH client' 'ServerAliveCountMax:' 3) || return; opts=$(ui_checklist 'SSH client' 'Global SSH client options.' tcp 'TCP keepalive' on hash 'Hash known hosts' on compression Compression off agent 'Forward SSH agent' off x11 'Forward X11' off strict 'Strict host-key checking' on control 'Connection multiplexing' on identities 'IdentitiesOnly' off) || return; body="Host $host\n    ServerAliveInterval $interval\n    ServerAliveCountMax $count"; selected_has "$opts" tcp && body="$body\n    TCPKeepAlive yes" || body="$body\n    TCPKeepAlive no"; selected_has "$opts" hash && body="$body\n    HashKnownHosts yes"; selected_has "$opts" compression && body="$body\n    Compression yes"; selected_has "$opts" agent && body="$body\n    ForwardAgent yes"; selected_has "$opts" x11 && body="$body\n    ForwardX11 yes"; selected_has "$opts" strict && body="$body\n    StrictHostKeyChecking ask" || body="$body\n    StrictHostKeyChecking no"; selected_has "$opts" control && body="$body\n    ControlMaster auto\n    ControlPersist 10m\n    ControlPath ~/.ssh/cm-%C"; selected_has "$opts" identities && body="$body\n    IdentitiesOnly yes"; replace_block "$f" ssh_config-options "$body"; chmod 600 "$f" 2>/dev/null || true; }

starship_wizard(){ f=$1; newline=$(ui_yesno Starship 'Add a blank line before the prompt?' && echo true || echo false); timeout=$(ui_input Starship 'Command timeout in milliseconds:' 1000) || return; format=$(ui_input Starship 'Prompt format:' '$username$hostname$directory$git_branch$git_status$line_break$character') || return; opts=$(ui_checklist Starship 'Modules to configure.' username Username on hostname Hostname on directory Directory on gitbranch 'Git branch' on gitstatus 'Git status' on duration 'Command duration' off jobs Jobs off memory 'Memory usage' off time Time off package Package off python Python off node Node.js off rust Rust off) || return; body="add_newline = $newline\ncommand_timeout = $timeout\nformat = \"$format\""; for x in username hostname directory gitbranch gitstatus duration jobs memory time package python node rust; do selected_has "$opts" "$x" || continue; case $x in gitbranch) m=git_branch;; gitstatus) m=git_status;; duration) m=cmd_duration;; memory) m=memory_usage;; node) m=nodejs;; *) m=$x;; esac; body="$body\n[$m]\ndisabled = false"; done; replace_block "$f" starship-options "$body"; }

profile_wizard(){ f=$1; path=$(ui_input Profile 'Additional PATH entries (colon-separated, blank for none):' '') || return; umask=$(ui_input Profile 'Default umask:' 022) || return; pager=$(ui_input Profile 'PAGER command:' less) || return; lang=$(ui_input Profile 'LANG value (blank preserves system):' '') || return; body="# Login profile options selected through TUI\numask $umask\nexport PAGER=$pager"; [ -n "$path" ] && body="$body\nexport PATH=\"$path:\$PATH\""; [ -n "$lang" ] && body="$body\nexport LANG=$lang"; replace_block "$f" profile-options "$body"; }

ash_wizard(){ f=$1; prompt=$(ui_input Ash 'PS1 prompt:' '\u@\h:\w\$ ') || return; opts=$(ui_checklist Ash 'Ash options.' aliases 'Load ~/.aliases' on env 'Load ~/.profile' off vi 'Vi editing mode' off noclobber 'Prevent accidental overwrite' off) || return; body="# Ash options selected through TUI\nPS1='$prompt'"; selected_has "$opts" aliases && body="$body\n[ -f \"\$HOME/.aliases\" ] && . \"\$HOME/.aliases\""; selected_has "$opts" env && body="$body\n[ -f \"\$HOME/.profile\" ] && . \"\$HOME/.profile\""; selected_has "$opts" vi && body="$body\nset -o vi"; selected_has "$opts" noclobber && body="$body\nset -C"; replace_block "$f" ashrc-options "$body"; }
