#!/bin/sh
languages_menu(){ while :; do c=$(ui_menu 'Language ecosystems' 'Configure package managers and development environments.' python 'Python, pip, pipx, uv, Poetry' node 'Node.js, npm, pnpm, Yarn' rust 'Rust and Cargo' go 'Go environment' java 'Java, Maven, Gradle' swift 'Swift environment diagnostics' back Back) || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in python) language_python_menu;; node) language_node_menu;; rust) language_rust_menu;; go) language_go_menu;; java) language_java_menu;; swift) language_swift_menu;; back) return;; esac; done; }
language_python_menu(){ while :; do c=$(ui_menu Python "python3: $(status_word python3)" install 'Install Python bundle' pip 'Configure pip' venv 'Create virtual environment' pipx 'Install/configure pipx' uv 'Install/configure uv' back Back) || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in install) pkg_install python3 python3-pip python3-venv pipx;; pip) mkdir -p "$CURRENT_HOME/.config/pip"; config_entry_menu pip "$CURRENT_HOME/.config/pip/pip.conf" pip;; venv) d=$(ui_input venv 'Environment path' "$CURRENT_HOME/.venvs/default") || continue; python3 -m venv "$d" && ui_msg venv "Created $d";; pipx) pkg_install pipx; run_capture pipx pipx ensurepath;; uv) pkg_install uv 2>/dev/null || ui_msg uv 'Install uv with its supported package/source method for this distribution.';; back) return;; esac; done; }
language_node_menu(){ while :; do c=$(ui_menu Node "node: $(status_word node)" install 'Install Node and npm' npm 'Configure npm' manager 'Select package manager' global 'Set user global prefix' back Back) || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in install) pkg_install nodejs npm;; npm) config_entry_menu npm "$CURRENT_HOME/.npmrc" npmrc;; manager) m=$(ui_menu Manager 'Select package manager.' npm npm pnpm pnpm yarn Yarn bun Bun) || continue; pkg_install "$m";; global) mkdir -p "$CURRENT_HOME/.local/npm"; replace_block "$CURRENT_HOME/.npmrc" prefix 'prefix=${HOME}/.local/npm'; replace_block "$CURRENT_HOME/.profile" npm-path 'export PATH="$HOME/.local/npm/bin:$PATH"';; back) return;; esac; done; }
language_rust_menu(){ while :; do c=$(ui_menu Rust "cargo: $(status_word cargo)" install 'Install rust/cargo' config 'Configure Cargo' target 'Add target triple' vendor 'Configure vendored sources' back Back) || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in install) pkg_install rust cargo;; config) mkdir -p "$CURRENT_HOME/.cargo"; config_entry_menu Cargo "$CURRENT_HOME/.cargo/config.toml" cargo;; target) t=$(ui_input Target 'Rust target triple' aarch64-unknown-linux-gnu) || continue; have rustup && run_capture rustup rustup target add "$t" || ui_msg rustup 'rustup is not installed.';; vendor) ui_msg Vendor 'Run cargo vendor in a project, then add the generated source replacement to .cargo/config.toml.';; back) return;; esac; done; }
language_go_menu(){ while :; do c=$(ui_menu Go "go: $(status_word go)" install 'Install Go' env 'Configure GOPATH and cache' proxy 'Set GOPROXY' private 'Set GOPRIVATE' back Back) || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in install) pkg_install go golang;; env) replace_block "$CURRENT_HOME/.profile" go 'export GOPATH="$HOME/go"\nexport GOMODCACHE="$HOME/.cache/go-mod"\nexport GOCACHE="$HOME/.cache/go-build"\nexport PATH="$GOPATH/bin:$PATH"';; proxy) v=$(ui_input GOPROXY 'Proxy value' 'https://proxy.golang.org,direct') || continue; replace_block "$CURRENT_HOME/.profile" goproxy "export GOPROXY='$v'";; private) v=$(ui_input GOPRIVATE 'Private module patterns' '') || continue; replace_block "$CURRENT_HOME/.profile" goprivate "export GOPRIVATE='$v'";; back) return;; esac; done; }
language_java_menu(){ while :; do c=$(ui_menu Java "java: $(status_word java)" install 'Install JDK' maven 'Install/configure Maven' gradle 'Install/configure Gradle' env 'Set JAVA_HOME' back Back) || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in install) pkg_install openjdk17-jdk 2>/dev/null || pkg_install openjdk17;; maven) pkg_install maven; mkdir -p "$CURRENT_HOME/.m2"; edit_file "$CURRENT_HOME/.m2/settings.xml";; gradle) pkg_install gradle; mkdir -p "$CURRENT_HOME/.gradle"; edit_file "$CURRENT_HOME/.gradle/gradle.properties";; env) p=$(dirname "$(dirname "$(command -v java 2>/dev/null || echo /usr/bin/java)")"); replace_block "$CURRENT_HOME/.profile" java "export JAVA_HOME='$p'\nexport PATH=\"\$JAVA_HOME/bin:\$PATH\"";; back) return;; esac; done; }
language_swift_menu(){ while :; do c=$(ui_menu Swift "swift: $(status_word swift)" inspect 'Inspect Swift environment' env 'Configure library paths' test 'Compile test' back Back) || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in inspect) run_capture Swift sh -c 'swift --version; command -v swift; ldd "$(command -v swift)" 2>/dev/null || true';; env) replace_block "$CURRENT_HOME/.profile" swift 'export SWIFTLY_HOME_DIR="$HOME/.local/share/swiftly"\nexport PATH="$SWIFTLY_HOME_DIR/bin:$PATH"';; test) cat >"$TMP_DIR/t.swift" <<'EOF'
print("Swift works")
EOF
run_capture Swift swift "$TMP_DIR/t.swift";; back) return;; esac; done; }
