#!/bin/sh
v83_transactions_view(){ ui_text 'Transaction journal' "$(transaction_list 2>/dev/null || true)"; }
v83_locks_view(){ rootfs_lock_cleanup_stale; ui_text 'RootFS locks' "$(rootfs_lock_report)"; }
v83_integrity_create(){ root=$(active_rootfs); [ -d "$root" ] || { ui_msg Error 'Select an active RootFS first.'; return 1; }; name=$(ui_input 'Integrity baseline' 'Baseline name:' default) || return; out=$(integrity_create_baseline "$root" "$name") || { ui_msg Error 'Unable to create baseline.'; return 1; }; ui_msg 'Integrity baseline' "$out"; }
v83_integrity_verify(){ files=$(integrity_list_baselines); [ -n "$files" ] || { ui_msg 'Integrity baseline' 'No baselines exist.'; return; }; args=; for f in $files; do args="$args $(basename "$f" .tsv) $f"; done; # shellcheck disable=SC2086
  choice=$(eval "ui_menu 'Verify baseline' 'Select a baseline.' $args") || return; file="$V83_BASELINE_DIR/$choice.tsv"; out="$V83_STATE_DIR/verify-$choice-$(date +%Y%m%d-%H%M%S).txt"; if integrity_verify_baseline "$file" >"$out"; then echo 'OK: no changes detected.' >>"$out"; fi; ui_text 'Integrity verification' "$(cat "$out")"; }
v83_transaction_demo(){ root=$(active_rootfs); [ -d "$root" ] || { ui_msg Error 'Select an active RootFS first.'; return 1; }; rootfs_lock_acquire "$root" transaction 10 || { ui_msg Error 'RootFS is locked by another operation.'; return 1; }; trap 'rootfs_lock_release' 0 1 2 15; id=$(transaction_begin configuration "$root") || return; for p in "$root/etc/hosts" "$root/etc/resolv.conf"; do transaction_backup_path "$p" || true; done; transaction_commit; rootfs_lock_release; trap - 0 1 2 15; ui_msg 'Transaction created' "$id"; }
v83_rollback_menu(){ rows=$(transaction_list); [ -n "$rows" ] || { ui_msg Transactions 'No transactions found.'; return; }; args=; while IFS="$(printf '\t')" read -r id status name root; do args="$args $id $status:$name"; done <<EOF2
$rows
EOF2
  # shellcheck disable=SC2086
  choice=$(eval "ui_menu 'Rollback transaction' 'Select a transaction to restore.' $args") || return; ui_confirm 'Rollback transaction' "Restore files recorded by $choice?" || return; transaction_rollback_dir "$V83_TX_DIR/$choice" && ui_msg Rollback 'Rollback completed.' || ui_msg Error 'Rollback failed.'; }
v83_operations_report(){ printf '%s %s — Operations Hardening\n' "$PROGRAM" "$VERSION"; printf 'Transactions: %s\n' "$(find "$V83_TX_DIR" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l | tr -d ' ')"; printf 'Locks: %s\n' "$(find "$V83_LOCK_DIR" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l | tr -d ' ')"; printf 'Baselines: %s\n' "$(find "$V83_BASELINE_DIR" -name '*.tsv' -type f 2>/dev/null | wc -l | tr -d ' ')"; }
v83_operations_menu(){ while :; do c=$(ui_menu 'Operations Hardening' 'Transactions, RootFS locks, integrity baselines and recovery journals.' transactions 'View transaction journal' create 'Create configuration transaction' rollback 'Rollback a transaction' locks 'View and clean RootFS locks' baseline 'Create integrity baseline' verify 'Verify integrity baseline' report 'Operations report') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in transactions) v83_transactions_view;; create) v83_transaction_demo;; rollback) v83_rollback_menu;; locks) v83_locks_view;; baseline) v83_integrity_create;; verify) v83_integrity_verify;; report) ui_text 'Operations report' "$(v83_operations_report)";; esac; done; }
