#!/bin/sh
quick_setup_pkg_name(){ key=$1; case "$PKG_MGR:$key" in
 apt:dialog) echo dialog;; apk:dialog) echo dialog;; pacman:dialog) echo dialog;;
 apt:build) echo build-essential;; apk:build) echo 'build-base';; pacman:build) echo base-devel;; dnf:build|yum:build) echo '@development-tools';; xbps:build) echo base-devel;; emerge:build) echo sys-devel/gcc;; zypper:build) echo -t pattern devel_basis;;
 apt:fd) echo fd-find;; apk:fd|pacman:fd|dnf:fd|yum:fd|xbps:fd|zypper:fd) echo fd;;
 apt:bat) echo bat;; apk:bat|pacman:bat|dnf:bat|yum:bat|xbps:bat|zypper:bat) echo bat;;
 apt:eza) echo eza;; apk:eza|pacman:eza|dnf:eza|yum:eza|xbps:eza|zypper:eza) echo eza;;
 apt:python) echo 'python3 python3-pip python3-venv pipx';; apk:python) echo 'python3 py3-pip py3-virtualenv pipx';; pacman:python) echo 'python python-pip python-virtualenv python-pipx';; dnf:python|yum:python) echo 'python3 python3-pip pipx';; xbps:python) echo 'python3 python3-pipx';; zypper:python) echo 'python3 python3-pip python3-pipx';;
 apt:ssh) echo 'openssh-client openssh-server';; apk:ssh) echo openssh;; pacman:ssh) echo openssh;; dnf:ssh|yum:ssh) echo openssh-server;; xbps:ssh) echo openssh;; zypper:ssh) echo openssh;;
 *:*) echo "$key";; esac; }
quick_setup_install_keys(){ keys=$*; pkgs=''; for k in $keys; do p=$(quick_setup_pkg_name "$k"); pkgs="$pkgs $p"; done; [ -n "$pkgs" ] || return 0; # shellcheck disable=SC2086
 pkg_install $pkgs; }
quick_setup_required(){ quick_setup_install_keys dialog git curl wget ca-certificates openssl tar gzip xz coreutils findutils grep sed awk procps util-linux; }
quick_setup_recommended(){ quick_setup_install_keys dialog git curl wget ca-certificates openssl tar gzip xz zstd unzip zip rsync jq less file tree ncurses bash bash-completion zsh fish nano vim neovim tmux screen htop btop ripgrep fd fzf bat eza python ssh sudo doas cron logrotate; }
quick_setup_developer(){ quick_setup_recommended; quick_setup_install_keys build cmake ninja meson pkg-config make gcc clang gdb strace ltrace ccache git-lfs go rust cargo nodejs npm; }
quick_setup_aok(){ quick_setup_recommended; quick_setup_install_keys debootstrap qemu-user-static binfmt-support proot fakeroot fakechroot dpkg-dev apt-utils squashfs-tools cpio pax pigz pixz lz4 zstd rsync patch diffutils findutils file binutils elfutils; }
quick_setup_custom(){ sel=$(ui_checklist 'Quick setup package selection' 'Select package groups and useful initial-system tools.' required 'Project runtime requirements' on recommended 'Recommended terminal/system tools' on developer 'Compilers and development environment' off aok 'AOK/rootfs build and analysis tools' off network 'Network diagnostics and transfer tools' off security 'Security and permission audit tools' off monitoring 'Monitoring and process tools' off files 'File managers and navigation tools' off shells 'Shells, prompts and completion tools' off editors 'Editors and editor dependencies' off) || return; for item in $sel; do case $item in required) quick_setup_required;; recommended) quick_setup_recommended;; developer) quick_setup_developer;; aok) quick_setup_aok;; network) quick_setup_install_keys bind-tools dnsutils iproute2 iputils netcat-openbsd socat mtr traceroute whois nmap openssh rsync curl wget openssl;; security) quick_setup_install_keys sudo doas acl attr gnupg openssl shadow audit lynis rkhunter;; monitoring) quick_setup_install_keys procps htop btop glances iotop sysstat lsof strace time;; files) quick_setup_install_keys nnn lf ranger mc tere yazi tree fzf ripgrep fd bat eza;; shells) quick_setup_install_keys bash bash-completion zsh fish ksh mksh dash starship fzf zoxide direnv;; editors) quick_setup_install_keys nano vim neovim micro helix emacs git curl nodejs npm python;; esac; done; }
quick_setup_audit(){ out=$REPORT_DIR/quick-setup-audit.txt; { echo 'Quick system setup audit'; echo '========================'; for c in sh git curl wget tar gzip sed awk grep find xargs dialog whiptail bash zsh fish nano vim nvim tmux screen ssh sudo doas python3 pipx cargo rustc go node npm nnn lf ranger yazi mc tere; do if have "$c"; then printf '%-18s installed: %s\n' "$c" "$(command -v "$c")"; else printf '%-18s missing\n' "$c"; fi; done; } >"$out"; ui_text 'Quick setup audit' "$(cat "$out")"; }
quick_system_setup_menu(){ while :; do c=$(ui_menu 'Quick system setup' 'Install project requirements and useful packages for a fresh iSH-AOK or Linux root filesystem.' audit 'Audit installed requirements' required 'Install minimum project requirements' recommended 'Install recommended initial-system tools' developer 'Install full developer workstation bundle' aok 'Install AOK/rootfs builder bundle' custom 'Select package groups individually' update 'Update package indexes first') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in audit) quick_setup_audit;; required) run_capture 'Install required packages' quick_setup_required;; recommended) run_capture 'Install recommended packages' quick_setup_recommended;; developer) run_capture 'Install developer bundle' quick_setup_developer;; aok) run_capture 'Install AOK bundle' quick_setup_aok;; custom) quick_setup_custom;; update) run_capture 'Package index update' pkg_update;; esac; done; }
