#!/bin/sh
shell_config_center(){ while :; do c=$(ui_menu 'Shell configuration center' 'Generate complete defaults, add managed entries, inspect files, and remove individual managed sections.' defaults 'Generate shell defaults' add 'Add settings to shell files' blocks 'List/remove managed blocks' validate 'Validate shell configuration' plugins 'Shell plugin management') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in defaults) shell_defaults_menu;; add) shell_add_menu;; blocks) shell_blocks_menu;; validate) shell_validate_menu;; plugins) plugin_manager_menu shell;; esac; done; }

shell_file_pick(){ ui_menu 'Select shell file' 'Choose a configuration target.' bashrc "$CURRENT_HOME/.bashrc" bash_profile "$CURRENT_HOME/.bash_profile" profile "$CURRENT_HOME/.profile" zshrc "$CURRENT_HOME/.zshrc" ashrc "$CURRENT_HOME/.ashrc" kshrc "$CURRENT_HOME/.kshrc" fish "$CURRENT_HOME/.config/fish/config.fish" aliases "$CURRENT_HOME/.aliases"; }
shell_path_for(){ case $1 in bashrc) echo "$CURRENT_HOME/.bashrc";; bash_profile) echo "$CURRENT_HOME/.bash_profile";; profile) echo "$CURRENT_HOME/.profile";; zshrc) echo "$CURRENT_HOME/.zshrc";; ashrc) echo "$CURRENT_HOME/.ashrc";; kshrc) echo "$CURRENT_HOME/.kshrc";; fish) echo "$CURRENT_HOME/.config/fish/config.fish";; aliases) echo "$CURRENT_HOME/.aliases";; esac; }

shell_defaults_menu(){ while :; do c=$(ui_menu 'Generate shell defaults' 'Existing files are backed up. Choose recommended, minimal, developer, or iSH-AOK presets.' bash 'Bash defaults' zsh 'Zsh defaults' ash 'Ash defaults' profile 'POSIX login profile' fish 'Fish defaults' ksh 'Ksh defaults' all 'Generate defaults for installed shells') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in bash|zsh|ash|profile|fish|ksh) shell_generate_default "$c";; all) have bash && shell_generate_default bash recommended; have zsh && shell_generate_default zsh recommended; have fish && shell_generate_default fish recommended; have ksh && shell_generate_default ksh recommended; shell_generate_default ash recommended; shell_generate_default profile recommended;; esac; done; }

shell_generate_default(){ shell=$1; preset=${2:-}; [ -n "$preset" ] || preset=$(ui_radiolist "$shell defaults" 'Select a generated configuration preset.' minimal 'Small and portable' off recommended 'Recommended interactive defaults' on developer 'Development-oriented defaults' off aok 'iSH-AOK low-overhead defaults' off) || return; case $shell in bash) file=$CURRENT_HOME/.bashrc;; zsh) file=$CURRENT_HOME/.zshrc;; ash) file=$CURRENT_HOME/.ashrc;; profile) file=$CURRENT_HOME/.profile;; fish) file=$CURRENT_HOME/.config/fish/config.fish;; ksh) file=$CURRENT_HOME/.kshrc;; esac; body=$(shell_default_body "$shell" "$preset"); ui_text 'Generated preview' "$body"; ui_yesno 'Write defaults' "Replace $file with the generated $preset defaults?" || return; write_file "$file" 644 "$body"; ui_msg 'Shell defaults' "Generated $file"; }

shell_default_body(){ shell=$1; preset=$2; case $shell:$preset in
 bash:minimal) cat <<'EOT'
# ~/.bashrc generated by ish-aok-config
case $- in *i*) ;; *) return;; esac
PS1='\u@\h:\w\$ '
EOT
;;
 bash:recommended) cat <<'EOT'
# ~/.bashrc generated by ish-aok-config
case $- in *i*) ;; *) return;; esac
HISTCONTROL=ignoreboth:erasedups
HISTSIZE=5000
HISTFILESIZE=10000
HISTTIMEFORMAT='%F %T '
shopt -s histappend checkwinsize cmdhist lithist
shopt -s autocd 2>/dev/null || true
bind 'set completion-ignore-case on' 2>/dev/null || true
bind 'set show-all-if-ambiguous on' 2>/dev/null || true
[ -f "$HOME/.aliases" ] && . "$HOME/.aliases"
[ -f /etc/bash_completion ] && . /etc/bash_completion
PS1='\u@\h:\w\$ '
EOT
;;
 bash:developer) cat <<'EOT'
# ~/.bashrc developer preset generated by ish-aok-config
case $- in *i*) ;; *) return;; esac
HISTCONTROL=ignoreboth:erasedups
HISTSIZE=20000
HISTFILESIZE=40000
HISTTIMEFORMAT='%F %T '
shopt -s histappend checkwinsize cmdhist lithist globstar extglob nullglob
export EDITOR=${EDITOR:-nvim}
export VISUAL=${VISUAL:-$EDITOR}
export PAGER=${PAGER:-less}
export LESS='-FRX'
[ -d "$HOME/.local/bin" ] && PATH="$HOME/.local/bin:$PATH"
[ -d "$HOME/bin" ] && PATH="$HOME/bin:$PATH"
export PATH
[ -f "$HOME/.aliases" ] && . "$HOME/.aliases"
[ -f /etc/bash_completion ] && . /etc/bash_completion
command -v dircolors >/dev/null 2>&1 && eval "$(dircolors -b)"
PS1='\u@\h:\w\$ '
EOT
;;
 bash:aok) cat <<'EOT'
# ~/.bashrc iSH-AOK preset generated by ish-aok-config
case $- in *i*) ;; *) return;; esac
HISTCONTROL=ignoreboth:erasedups
HISTSIZE=3000
HISTFILESIZE=6000
shopt -s histappend checkwinsize
export EDITOR=${EDITOR:-nano}
export PAGER=${PAGER:-less}
export LESS='-FRX'
[ -d "$HOME/.local/bin" ] && PATH="$HOME/.local/bin:$PATH"
export PATH
[ -f "$HOME/.aliases" ] && . "$HOME/.aliases"
PS1='\u@\h:\w\$ '
EOT
;;
 zsh:minimal) cat <<'EOT'
PROMPT='%n@%m:%~%# '
EOT
;;
 zsh:recommended|zsh:aok) cat <<'EOT'
autoload -Uz compinit && compinit -C
HISTFILE=$HOME/.zsh_history
HISTSIZE=5000
SAVEHIST=10000
setopt APPEND_HISTORY SHARE_HISTORY HIST_IGNORE_ALL_DUPS HIST_REDUCE_BLANKS
setopt AUTO_CD AUTO_PUSHD PUSHD_IGNORE_DUPS INTERACTIVE_COMMENTS
[ -f "$HOME/.aliases" ] && source "$HOME/.aliases"
PROMPT='%n@%m:%~%# '
EOT
;;
 zsh:developer) cat <<'EOT'
autoload -Uz compinit && compinit -C
autoload -Uz colors && colors
HISTFILE=$HOME/.zsh_history
HISTSIZE=20000
SAVEHIST=40000
setopt APPEND_HISTORY SHARE_HISTORY EXTENDED_HISTORY HIST_IGNORE_ALL_DUPS HIST_REDUCE_BLANKS
setopt AUTO_CD AUTO_PUSHD PUSHD_IGNORE_DUPS INTERACTIVE_COMMENTS EXTENDED_GLOB
[ -d "$HOME/.local/bin" ] && path=("$HOME/.local/bin" $path)
[ -f "$HOME/.aliases" ] && source "$HOME/.aliases"
PROMPT='%F{green}%n@%m%f:%F{blue}%~%f%# '
EOT
;;
 ash:*|ksh:*) cat <<'EOT'
# Interactive shell defaults generated by ish-aok-config
[ -f "$HOME/.aliases" ] && . "$HOME/.aliases"
export EDITOR=${EDITOR:-vi}
export PAGER=${PAGER:-less}
PS1='\u@\h:\w\$ '
EOT
;;
 profile:*) cat <<'EOT'
# ~/.profile generated by ish-aok-config
[ -d "$HOME/bin" ] && PATH="$HOME/bin:$PATH"
[ -d "$HOME/.local/bin" ] && PATH="$HOME/.local/bin:$PATH"
export PATH
export EDITOR=${EDITOR:-vi}
export VISUAL=${VISUAL:-$EDITOR}
export PAGER=${PAGER:-less}
umask 022
[ -f "$HOME/.aliases" ] && . "$HOME/.aliases"
EOT
;;
 fish:*) cat <<'EOT'
# Fish defaults generated by ish-aok-config
set -gx EDITOR (set -q EDITOR; and echo $EDITOR; or echo vi)
set -gx PAGER (set -q PAGER; and echo $PAGER; or echo less)
fish_add_path -m $HOME/.local/bin $HOME/bin
set -g fish_greeting
EOT
;; esac; }

shell_add_menu(){ while :; do target=$(shell_file_pick) || return; file=$(shell_path_for "$target"); mkdir -p "$(dirname "$file")"; action=$(ui_menu "Add to ${file##*/}" 'Entries are stored in named managed blocks and can be replaced or removed later.' alias 'Add alias' function 'Add shell function' env 'Add environment variable' path 'Add PATH directory' source 'Source another file' command 'Run startup command' completion 'Add completion initialization' prompt 'Set prompt' options 'Add shell options' custom 'Add custom managed block' edit 'Open raw file') || continue; case $action in alias) shell_add_alias "$file";; function) shell_add_function "$file";; env) shell_add_env "$file";; path) shell_add_path "$file";; source) shell_add_source "$file";; command) shell_add_command "$file";; completion) shell_add_completion "$file" "$target";; prompt) shell_add_prompt "$file" "$target";; options) shell_add_options "$file" "$target";; custom) shell_add_custom "$file";; edit) edit_file "$file";; esac; done; }
valid_name(){ printf '%s' "$1" | grep -Eq '^[A-Za-z_][A-Za-z0-9_]*$'; }
shell_add_alias(){ f=$1; name=$(ui_input Alias 'Alias name:' '') || return; [ -n "$name" ] || return; cmd=$(ui_input Alias 'Command:' '') || return; [ -n "$cmd" ] || return; append_managed_entry "$f" aliases "alias $name='$(printf '%s' "$cmd"|sed "s/'/'\\\\''/g")'" "$name"; }
shell_add_function(){ f=$1; name=$(ui_input Function 'Function name:' '') || return; valid_name "$name" || { ui_msg Error 'Invalid function name.'; return; }; body=$(ui_input Function 'Function body (single line or semicolon-separated):' '') || return; append_managed_entry "$f" functions "$name() { $body; }" "$name"; }
shell_add_env(){ f=$1; name=$(ui_input Environment 'Variable name:' '') || return; valid_name "$name" || { ui_msg Error 'Invalid variable name.'; return; }; value=$(ui_input Environment 'Value:' '') || return; append_managed_entry "$f" environment "export $name='$(printf '%s' "$value"|sed "s/'/'\\\\''/g")'" "$name"; }
shell_add_path(){ f=$1; dir=$(ui_input PATH 'Directory to prepend:' '$HOME/.local/bin') || return; append_managed_entry "$f" path-extra "[ -d \"$dir\" ] && PATH=\"$dir:\$PATH\"\nexport PATH" "$dir"; }
shell_add_source(){ f=$1; src=$(ui_input Source 'File to source:' '$HOME/.aliases') || return; append_managed_entry "$f" sources "[ -f \"$src\" ] && . \"$src\"" "$src"; }
shell_add_command(){ f=$1; name=$(ui_input Command 'Entry name:' startup) || return; cmd=$(ui_input Command 'Command to run:' '') || return; append_managed_entry "$f" startup-commands "$cmd" "$name"; }
shell_add_completion(){ f=$1; target=$2; cmd=$(ui_input Completion 'Initialization command:' "$(case $target in bashrc) echo '[ -f /etc/bash_completion ] && . /etc/bash_completion';; zshrc) echo 'autoload -Uz compinit && compinit -C';; fish) echo '# Fish completions belong in ~/.config/fish/completions';; *) echo '';; esac)") || return; append_managed_entry "$f" completions "$cmd" completion; }
shell_add_prompt(){ f=$1; target=$2; case $target in zshrc) var=PROMPT; def='%n@%m:%~%# ';; fish) var=fish_prompt; def='function fish_prompt; echo -n (whoami)@(hostname):(prompt_pwd)\$ \x27; end';; *) var=PS1; def='\u@\h:\w\$ ';; esac; value=$(ui_input Prompt 'Prompt value or function:' "$def") || return; case $target in fish) line=$value;; *) line="$var='$(printf '%s' "$value"|sed "s/'/'\\\\''/g")'";; esac; replace_block "$f" prompt "$line"; }
shell_add_options(){ f=$1; target=$2; case $target in bashrc) opts=$(ui_checklist Bash 'Select Bash options.' histappend histappend on checkwinsize checkwinsize on globstar globstar off extglob extglob off nullglob nullglob off autocd autocd off nocaseglob nocaseglob off cdspell cdspell off) || return; body=''; for o in $opts; do body="$body\nshopt -s $o"; done;; zshrc) opts=$(ui_checklist Zsh 'Select Zsh options.' autocd AUTO_CD on autopushd AUTO_PUSHD on sharehistory SHARE_HISTORY on extendedglob EXTENDED_GLOB off correct CORRECT off interactivecomments INTERACTIVE_COMMENTS on) || return; body=''; for o in $opts; do case $o in autocd) o=AUTO_CD;; autopushd) o=AUTO_PUSHD;; sharehistory) o=SHARE_HISTORY;; extendedglob) o=EXTENDED_GLOB;; correct) o=CORRECT;; interactivecomments) o=INTERACTIVE_COMMENTS;; esac; body="$body\nsetopt $o"; done;; *) body=$(ui_input Options 'Shell option command(s):' '') || return;; esac; replace_block "$f" shell-options "$body"; }
shell_add_custom(){ f=$1; name=$(ui_input Block 'Managed block name:' custom) || return; body=$(ui_input Block 'Content (use \\n for line breaks):' '') || return; replace_block "$f" "$name" "$body"; }
append_managed_entry(){ f=$1; block=$2; line=$3; key=$4; b="# >>> ish-aok-config: $block >>>"; e="# <<< ish-aok-config: $block <<<"; [ -f "$f" ] || write_file "$f" 644 ''; current=$(awk -v b="$b" -v e="$e" '$0==b{s=1;next}$0==e{s=0} s{print}' "$f" 2>/dev/null); printf '%s\n' "$current" | grep -Fq "$key" && { ui_msg Existing "An entry matching '$key' already exists in $block."; return; }; [ -n "$current" ] && body="$current\n$line" || body=$line; replace_block "$f" "$block" "$body"; }

shell_blocks_menu(){ target=$(shell_file_pick) || return; f=$(shell_path_for "$target"); [ -f "$f" ] || { ui_msg Blocks 'File does not exist.'; return; }; blocks=$(sed -n 's/^# >>> ish-aok-config: \(.*\) >>>$/\1/p' "$f"); [ -n "$blocks" ] || { ui_msg Blocks 'No managed blocks found.'; return; }; set --; while IFS= read -r block; do [ -n "$block" ] && set -- "$@" "$block" 'Remove this managed block'; done <<EOF2
$blocks
EOF2
choice=$(ui_menu 'Managed blocks' "Choose a block to remove from $f" "$@") || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; ui_yesno Blocks "Remove managed block '$choice'?" && remove_managed_block "$f" "$choice"; }
shell_validate_menu(){ target=$(shell_file_pick) || return; f=$(shell_path_for "$target"); [ -f "$f" ] || { ui_msg Validate 'File does not exist.'; return; }; case $target in bashrc|bash_profile) have bash && run_capture 'Bash syntax' bash -n "$f" || ui_msg Validate 'Bash is not installed.';; zshrc) have zsh && run_capture 'Zsh syntax' zsh -n "$f" || ui_msg Validate 'Zsh is not installed.';; fish) have fish && run_capture 'Fish syntax' fish -n "$f" || ui_msg Validate 'Fish is not installed.';; *) run_capture 'POSIX shell syntax' sh -n "$f";; esac; }
