#!/bin/sh
v6_command_output(){ title=$1; shift; "$@" >"$TMP_DIR/v6-output" 2>&1 || true; ui_text "$title" "$(cat "$TMP_DIR/v6-output")"; }

platform_note(){ ui_msg "$1" "$2\n\nAvailability depends on the active distribution and iSH-AOK kernel capabilities."; }

configuration_profiles_center(){ while :; do registry_menu profiles 'Configuration profiles' 'Choose a complete reusable preset. Every profile asks before package installation or configuration changes.' || return; done; }
apply_system_profile(){ profile=${5:-$1}; ui_yesno 'Apply system profile' "Apply profile: $profile?\n\nA configuration backup will be created first." || return; backup_common >/dev/null 2>&1 || true; case $profile in minimal) quick_setup_required; performance_profile_block minimal 1 500 5 2>/dev/null || true;; ssh) quick_setup_recommended; have configure_sshd && configure_sshd || true;; developer) quick_setup_developer; performance_profile_block developer 2 3000 0 2>/dev/null || true;; builder) quick_setup_aok; performance_profile_block developer 2 3000 0 2>/dev/null || true;; lowmem) performance_profile_block ultra 1 300 10 2>/dev/null || true;; secure) privilege_admin_menu; ssh_menu;; portable) quick_setup_required; performance_profile_block low 1 750 5 2>/dev/null || true;; ci) quick_setup_developer; replace_block "$CURRENT_HOME/.profile" ci-profile 'export CI=1\nexport MAKEFLAGS="-j1"\nexport CARGO_TERM_COLOR=always';; esac; ui_msg Profile "Profile applied: $profile"; }

theme_center(){ while :; do registry_menu themes 'Unified theme center' 'Apply coordinated managed theme blocks. Individual tool wizards remain available for detailed changes.' || return; done; }
apply_theme_profile(){ theme=${5:-$1}; case $theme in light) bg=light; vim='default'; bat='GitHub'; btop='Default';; gruvbox) bg=dark; vim='gruvbox'; bat='gruvbox-dark'; btop='gruvbox_dark';; dracula) bg=dark; vim='dracula'; bat='Dracula'; btop='dracula';; catppuccin) bg=dark; vim='catppuccin'; bat='Catppuccin Mocha'; btop='catppuccin_mocha';; nord) bg=dark; vim='nord'; bat='Nord'; btop='nord';; tokyonight) bg=dark; vim='tokyonight'; bat='OneHalfDark'; btop='tokyo-night';; minimal) bg=dark; vim='default'; bat='ansi'; btop='Default';; *) bg=dark; vim='default'; bat='ansi'; btop='Default';; esac; replace_block "$CURRENT_HOME/.profile" unified-theme "export ISH_AOK_THEME='$theme'\nexport BAT_THEME='$bat'\nexport FZF_DEFAULT_OPTS=\"\${FZF_DEFAULT_OPTS:-} --layout=reverse --border\""; replace_block "$CURRENT_HOME/.vimrc" unified-theme "set background=$bg\ncolorscheme $vim"; mkdir -p "$CURRENT_HOME/.config/btop" 2>/dev/null || true; [ -f "$CURRENT_HOME/.config/btop/btop.conf" ] || : >"$CURRENT_HOME/.config/btop/btop.conf"; replace_block "$CURRENT_HOME/.config/btop/btop.conf" unified-theme "color_theme = \"$btop\""; ui_msg Theme "Applied managed theme profile: $theme"; }

network_center(){ while :; do c=$(ui_menu 'Network center' 'Network inspection and configuration helpers.' existing 'Existing network and DNS tools' interfaces 'Interface and address report' routes 'Routing table and policy rules' dns 'Resolver and hosts management' ports 'Listening ports and sockets' tunnel 'SSH tunnel command builder' firewall 'Firewall capability and rules report' wireguard 'WireGuard setup helper' tailscale 'Tailscale setup helper' proxy 'Proxy environment profile') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in existing) network_tools_menu;; interfaces) v6_command_output Interfaces sh -c 'ip addr 2>/dev/null || ifconfig -a 2>/dev/null';; routes) v6_command_output Routes sh -c 'ip route show table all 2>/dev/null; ip rule 2>/dev/null';; dns) network_dns_profile;; ports) v6_command_output Ports sh -c 'ss -lntup 2>/dev/null || netstat -lntup 2>/dev/null';; tunnel) ssh_tunnel_builder;; firewall) v6_command_output Firewall sh -c 'nft list ruleset 2>/dev/null || iptables-save 2>/dev/null || true';; wireguard) network_install_tool wireguard-tools wg;; tailscale) network_install_tool tailscale tailscale;; proxy) network_proxy_profile;; esac; done; }
network_dns_profile(){ c=$(ui_menu DNS 'Resolver and hosts options.' view 'View resolver and hosts files' cloudflare 'Use Cloudflare resolvers' google 'Use Google resolvers' quad9 'Use Quad9 resolvers' custom 'Set custom resolver addresses' edit_hosts 'Add a managed hosts entry') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in view) ui_text DNS "$(cat /etc/resolv.conf /etc/hosts 2>/dev/null)";; cloudflare) data='nameserver 1.1.1.1\nnameserver 1.0.0.1';; google) data='nameserver 8.8.8.8\nnameserver 8.8.4.4';; quad9) data='nameserver 9.9.9.9\nnameserver 149.112.112.112';; custom) ns=$(ui_input DNS 'Space-separated resolver addresses:' '') || return; data=''; for n in $ns; do data="$data\nnameserver $n"; done;; edit_hosts) ip=$(ui_input Hosts 'Address:' '127.0.0.1') || return; name=$(ui_input Hosts 'Hostname:' '') || return; append_unique /etc/hosts "$ip $name"; return;; esac; [ -n "${data:-}" ] && { need_root || return; write_file /etc/resolv.conf 644 "$data"; }; }
ssh_tunnel_builder(){ mode=$(ui_menu Tunnel 'Choose tunnel type.' local 'Local forward (-L)' reverse 'Reverse forward (-R)' socks 'SOCKS proxy (-D)') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; host=$(ui_input Tunnel 'SSH destination user@host:' '') || return; case $mode in local) spec=$(ui_input Tunnel 'local_port:target_host:target_port:' '8080:127.0.0.1:80') || return; cmd="ssh -N -L $spec $host";; reverse) spec=$(ui_input Tunnel 'remote_port:target_host:target_port:' '2222:127.0.0.1:22') || return; cmd="ssh -N -R $spec $host";; socks) port=$(ui_input Tunnel 'SOCKS port:' '1080') || return; cmd="ssh -N -D $port $host";; esac; ui_text Tunnel "$cmd"; }
network_install_tool(){ pkg=$1 cmd=$2; have "$cmd" && { ui_msg Network "$cmd is already installed."; return; }; ui_yesno Network "Install $pkg?" && run_capture "Installing $pkg" pkg_install "$pkg"; }
network_proxy_profile(){ http=$(ui_input Proxy 'HTTP proxy URL (blank disables):' '') || return; https=$(ui_input Proxy 'HTTPS proxy URL:' "$http") || return; no=$(ui_input Proxy 'NO_PROXY list:' 'localhost,127.0.0.1') || return; [ -n "$http$https" ] && body="export http_proxy='$http'\nexport https_proxy='$https'\nexport HTTP_PROXY='$http'\nexport HTTPS_PROXY='$https'\nexport NO_PROXY='$no'" || body='unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY NO_PROXY'; replace_block "$CURRENT_HOME/.profile" proxy "$body"; }

storage_center_v6(){ while :; do c=$(ui_menu 'Disk and storage center' 'Storage, swap and image-management operations.' existing 'Existing storage tools' mounts 'Mount management' usage 'Largest filesystem paths' swap 'Swap status and file wizard' zram 'zram capability and setup notes' loop 'Loop-device and image mounting' labels 'Filesystem UUID and label report' trim 'Discard/TRIM capability report' fsck 'Filesystem-check command builder') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in existing) storage_tools_menu;; mounts) mount_manager_menu;; usage) path=$(ui_input Storage 'Path to inspect:' '/') || continue; v6_command_output Storage sh -c "du -x -h '$path' 2>/dev/null | sort -h | tail -n 100";; swap) storage_swap_wizard;; zram) v6_command_output zram sh -c 'cat /proc/swaps 2>/dev/null; ls /sys/block/zram* 2>/dev/null; command -v zramctl >/dev/null && zramctl';; loop) storage_loop_wizard;; labels) v6_command_output Labels sh -c 'blkid 2>/dev/null; lsblk -f 2>/dev/null';; trim) v6_command_output TRIM sh -c 'command -v fstrim >/dev/null && fstrim --version; findmnt -D 2>/dev/null';; fsck) dev=$(ui_input fsck 'Device or image:' '') || continue; type=$(ui_input fsck 'Filesystem type (optional):' '') || continue; ui_text fsck "Recommended offline command:\nfsck ${type:+-t $type} -f '$dev'";; esac; done; }
storage_swap_wizard(){ c=$(ui_menu Swap 'Swap management.' status 'Show active swap' create 'Create and enable swap file' disable 'Disable a swap path') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in status) v6_command_output Swap sh -c 'cat /proc/swaps 2>/dev/null; free -h 2>/dev/null';; create) file=$(ui_input Swap 'Swap file path:' '/swapfile') || return; mb=$(ui_input Swap 'Size in MiB:' '512') || return; need_root || return; run_capture Swap sh -c "dd if=/dev/zero of='$file' bs=1M count='$mb' && chmod 600 '$file' && mkswap '$file' && swapon '$file'";; disable) file=$(ui_input Swap 'Swap path:' '/swapfile') || return; run_capture Swap as_root swapoff "$file";; esac; }
storage_loop_wizard(){ image=$(ui_input Loop 'Image file:' '') || return; target=$(ui_input Loop 'Mountpoint:' '/mnt/image') || return; [ -f "$image" ] || { ui_msg Loop 'Image file not found.'; return; }; need_root || return; run_capture Loop as_root mkdir -p "$target"; run_capture Loop as_root mount -o loop "$image" "$target"; }

users_permissions_center(){ while :; do c=$(ui_menu 'Users and permissions' 'Account, group and filesystem permission management.' users 'List users and login shells' add 'Create a user' lock 'Lock or unlock an account' groups 'Manage group membership' shell 'Change default login shell' keys 'Manage authorized SSH keys' aging 'Password aging report' limits 'User resource-limit profile' chmod 'Permission wizard' ownership 'Ownership wizard' insecure 'Permission security audit' admin 'Sudo and doas management') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in users) v6_command_output Users sh -c "awk -F: '{printf \"%-20s uid=%-6s shell=%s\\n\",\$1,\$3,\$7}' /etc/passwd";; add) user_add_wizard;; lock) user_lock_wizard;; groups) user_group_wizard;; shell) user_shell_wizard;; keys) user_keys_wizard;; aging) v6_command_output Aging sh -c 'command -v chage >/dev/null && while IFS=: read -r u x; do chage -l "$u" 2>/dev/null | sed "s/^/$u: /"; done </etc/passwd';; limits) user_limits_wizard;; chmod) permissions_mode_wizard;; ownership) ownership_wizard;; insecure) permission_audit;; admin) privilege_admin_menu;; esac; done; }
user_add_wizard(){ u=$(ui_input User 'Username:' '') || return; [ -n "$u" ] || return; shell=$(ui_input User 'Login shell:' '/bin/sh') || return; need_root || return; if have adduser; then run_capture User as_root adduser "$u"; else run_capture User as_root useradd -m -s "$shell" "$u"; fi; }
user_lock_wizard(){ u=$(ui_input User 'Username:' "$CURRENT_USER") || return; a=$(ui_menu User 'Account state action.' lock Lock unlock Unlock) || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; need_root || return; case $a in lock) run_capture User as_root passwd -l "$u";; unlock) run_capture User as_root passwd -u "$u";; esac; }
user_group_wizard(){ u=$(ui_input Groups 'Username:' "$CURRENT_USER") || return; g=$(ui_input Groups 'Group:' '') || return; need_root || return; if have usermod; then run_capture Groups as_root usermod -aG "$g" "$u"; elif have addgroup; then run_capture Groups as_root addgroup "$u" "$g"; fi; }
user_shell_wizard(){ u=$(ui_input Shell 'Username:' "$CURRENT_USER") || return; s=$(ui_input Shell 'Shell path:' '/bin/bash') || return; need_root || return; run_capture Shell as_root chsh -s "$s" "$u"; }
user_keys_wizard(){ u=$(ui_input SSH 'Home directory owner:' "$CURRENT_USER") || return; home=$(awk -F: -v u="$u" '$1==u{print $6}' /etc/passwd); [ -n "$home" ] || home=$CURRENT_HOME; key=$(ui_input SSH 'Public key text:' '') || return; [ -n "$key" ] || return; mkdir -p "$home/.ssh" 2>/dev/null || as_root mkdir -p "$home/.ssh"; append_unique "$home/.ssh/authorized_keys" "$key"; chmod 700 "$home/.ssh" 2>/dev/null || true; chmod 600 "$home/.ssh/authorized_keys" 2>/dev/null || true; }
user_limits_wizard(){ u=$(ui_input Limits 'Username or @group:' "$CURRENT_USER") || return; nofile=$(ui_input Limits 'Open-file soft/hard limit:' '4096') || return; nproc=$(ui_input Limits 'Process soft/hard limit:' '1024') || return; write_file "/etc/security/limits.d/90-ish-aok-$CURRENT_USER.conf" 644 "$u soft nofile $nofile\n$u hard nofile $nofile\n$u soft nproc $nproc\n$u hard nproc $nproc"; }
permissions_mode_wizard(){ p=$(ui_input Permissions 'Path:' '') || return; mode=$(ui_input Permissions 'Octal mode:' '755') || return; recursive=$(ui_yesno Permissions 'Apply recursively?' && echo yes || echo no); need_root || return; [ "$recursive" = yes ] && run_capture Permissions as_root chmod -R "$mode" "$p" || run_capture Permissions as_root chmod "$mode" "$p"; }
ownership_wizard(){ p=$(ui_input Ownership 'Path:' '') || return; owner=$(ui_input Ownership 'Owner[:group]:' "$CURRENT_USER") || return; recursive=$(ui_yesno Ownership 'Apply recursively?' && echo yes || echo no); need_root || return; [ "$recursive" = yes ] && run_capture Ownership as_root chown -R "$owner" "$p" || run_capture Ownership as_root chown "$owner" "$p"; }
permission_audit(){ root=$(ui_input Audit 'Path to audit:' '/') || return; out=$REPORT_DIR/permission-audit-$(date +%Y%m%d-%H%M%S).txt; { printf '[World writable]\n'; find "$root" -xdev -type f -perm -0002 2>/dev/null | head -n 300; printf '\n[SUID/SGID]\n'; find "$root" -xdev -type f \( -perm -4000 -o -perm -2000 \) 2>/dev/null | head -n 300; printf '\n[No owner/group]\n'; find "$root" -xdev \( -nouser -o -nogroup \) 2>/dev/null | head -n 300; } >"$out"; ui_text Audit "$(cat "$out")"; }

backup_restore_center(){ while :; do c=$(ui_menu 'Backup and restore center' 'Create, verify and restore project or rootfs data.' existing 'Existing configuration backup tools' config 'Create configuration archive' state 'Back up project state' verify 'Verify archive integrity' restore 'Extract archive to a selected directory' rootfs 'Archive active rootfs' schedule 'Generate scheduled backup cron entry') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in existing) backup_menu;; config) backup_common; d=$(ls -dt "$BACKUP_DIR"/config-* 2>/dev/null | head -1); [ -n "$d" ] && run_capture Backup tar -czf "$d.tar.gz" -C "$BACKUP_DIR" "$(basename "$d")";; state) dest=$CURRENT_HOME/ish-aok-state-$(date +%Y%m%d-%H%M%S).tar.gz; run_capture Backup tar -czf "$dest" -C "$(dirname "$STATE_DIR")" "$(basename "$STATE_DIR")"; ui_msg Backup "$dest";; verify) f=$(ui_input Verify 'Archive:' '') || continue; archive_verify "$f";; restore) f=$(ui_input Restore 'Archive:' '') || continue; d=$(ui_input Restore 'Destination directory:' "$CURRENT_HOME/restore") || continue; mkdir -p "$d"; run_capture Restore tar -xf "$f" -C "$d";; rootfs) command -v aok_create_checksummed_archive >/dev/null 2>&1 && aok_create_checksummed_archive || aok_filesystems_menu;; schedule) backup_schedule_wizard;; esac; done; }
archive_verify(){ f=$1; [ -f "$f" ] || { ui_msg Verify 'Archive not found.'; return; }; case $f in *.tar.gz|*.tgz) cmd='tar -tzf';; *.tar.xz) cmd='tar -tJf';; *.tar.zst) cmd='tar --zstd -tf';; *.tar) cmd='tar -tf';; *) cmd='tar -tf';; esac; sh -c "$cmd '$f' >/dev/null" && ui_msg Verify 'Archive test passed.' || ui_msg Verify 'Archive test failed.'; }
backup_schedule_wizard(){ when=$(ui_input Schedule 'Cron expression:' '0 3 * * 0') || return; dest=$(ui_input Schedule 'Destination directory:' "$CURRENT_HOME/backups") || return; cmd="mkdir -p '$dest' && tar -czf '$dest/config-\$(date +\\%Y\\%m\\%d).tar.gz' '$CURRENT_HOME/.config' '$STATE_DIR'"; line="$when $cmd"; (crontab -l 2>/dev/null; printf '%s\n' "$line") | crontab -; ui_msg Schedule "$line"; }

monitoring_center(){ while :; do c=$(ui_menu 'Monitoring dashboard' 'Live and snapshot system diagnostics.' summary 'System summary' processes 'Top processes by memory' tree 'Process tree' memory 'Memory details' filesystem 'Filesystem usage' network 'Network sockets' openfiles 'Open files summary' pressure 'Kernel pressure and load' live 'Launch available interactive monitor' report 'Export monitoring report') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in summary) v6_command_output Summary sh -c 'uname -a; uptime; free -h 2>/dev/null; df -h 2>/dev/null';; processes) v6_command_output Processes sh -c 'ps aux 2>/dev/null | sort -k4 -nr | head -n 80';; tree) v6_command_output Tree sh -c 'pstree -ap 2>/dev/null || ps -ef';; memory) v6_command_output Memory sh -c 'cat /proc/meminfo 2>/dev/null; free -h 2>/dev/null';; filesystem) v6_command_output Filesystem sh -c 'df -h; df -i';; network) v6_command_output Network sh -c 'ss -s 2>/dev/null; ss -lntup 2>/dev/null';; openfiles) v6_command_output Files sh -c 'lsof 2>/dev/null | head -n 250';; pressure) v6_command_output Pressure sh -c 'cat /proc/loadavg 2>/dev/null; cat /proc/pressure/* 2>/dev/null';; live) for t in btop htop top; do have "$t" && { "$t"; break; }; done;; report) monitoring_export_report;; esac; done; }
monitoring_export_report(){ out=$REPORT_DIR/monitoring-$(date +%Y%m%d-%H%M%S).txt; { uname -a; uptime; free -h 2>/dev/null; df -h; ps aux 2>/dev/null | sort -k4 -nr | head -n 100; ss -lntup 2>/dev/null; } >"$out" 2>&1; ui_msg Report "$out"; }

container_center(){ while :; do c=$(ui_menu 'Container center' 'Container and isolation tools; kernel support varies under iSH-AOK.' detect 'Capability report' chroot 'AOK chroot tools' proot 'Install or launch proot' podman 'Install or inspect Podman' docker 'Install or inspect Docker' distrobox 'Install or inspect Distrobox' images 'List container images' containers 'List containers' volumes 'List volumes') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in detect) container_capability_report;; chroot) aok_chroot_menu;; proot) container_install_or_report proot proot '--version';; podman) container_install_or_report podman podman 'info';; docker) container_install_or_report docker docker 'info';; distrobox) container_install_or_report distrobox distrobox 'version';; images) v6_command_output Images sh -c 'podman images 2>/dev/null || docker images 2>/dev/null';; containers) v6_command_output Containers sh -c 'podman ps -a 2>/dev/null || docker ps -a 2>/dev/null';; volumes) v6_command_output Volumes sh -c 'podman volume ls 2>/dev/null || docker volume ls 2>/dev/null';; esac; done; }
container_capability_report(){ v6_command_output Containers sh -c 'printf "cgroups: "; [ -d /sys/fs/cgroup ] && echo yes || echo no; printf "namespaces: "; [ -r /proc/self/ns/mnt ] && echo yes || echo no; printf "user namespaces: "; [ -r /proc/sys/user/max_user_namespaces ] && cat /proc/sys/user/max_user_namespaces || echo unknown; for c in chroot proot podman docker distrobox bwrap unshare; do command -v "$c" >/dev/null && printf "%s: %s\n" "$c" "$(command -v "$c")"; done'; }
container_install_or_report(){ pkg=$1 cmd=$2 sub=$3; if have "$cmd"; then v6_command_output "$cmd" sh -c "$cmd $sub"; else ui_yesno "$cmd" "Install $pkg?" && run_capture "$cmd" pkg_install "$pkg"; fi; }

scheduler_center(){ while :; do c=$(ui_menu 'Scheduler center' 'Cron, at and periodic task management.' list 'List user cron jobs' add 'Add cron job' remove 'Remove cron jobs interactively' system 'List system cron directories' at 'Schedule one-time job with at' install 'Install scheduler tools' existing 'Existing scheduler tools') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in list) v6_command_output Cron crontab -l;; add) scheduler_add_cron;; remove) crontab -l >"$TMP_DIR/crontab" 2>/dev/null || :; edit_file "$TMP_DIR/crontab"; crontab "$TMP_DIR/crontab";; system) v6_command_output Cron sh -c 'find /etc/cron* /etc/periodic -maxdepth 2 -type f 2>/dev/null';; at) scheduler_at_job;; install) run_capture Scheduler pkg_install cron at 2>/dev/null || run_capture Scheduler pkg_install cronie at;; existing) cron_menu;; esac; done; }
scheduler_add_cron(){ expr=$(ui_input Cron 'Schedule expression:' '0 * * * *') || return; cmd=$(ui_input Cron 'Command:' '') || return; [ -n "$cmd" ] || return; (crontab -l 2>/dev/null; printf '%s %s\n' "$expr" "$cmd") | crontab -; }
scheduler_at_job(){ have at || { ui_msg at 'Install the at package first.'; return; }; when=$(ui_input at 'Time specification:' 'now + 1 hour') || return; cmd=$(ui_input at 'Command:' '') || return; printf '%s\n' "$cmd" | at "$when"; }

logging_center_v6(){ while :; do c=$(ui_menu 'Logging center' 'Search, follow, rotate and configure system logs.' existing 'Existing logging tools' files 'List log files and sizes' search 'Search logs' follow 'Follow a log file' rotate 'Run logrotate now' clean 'Clean old or oversized logs' syslog 'Install/configure syslog implementation' project 'Project operation log') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in existing) logging_tools_menu;; files) v6_command_output Logs sh -c 'find /var/log -type f -exec du -h {} \; 2>/dev/null | sort -h | tail -n 200';; search) q=$(ui_input Logs 'Search expression:' '') || continue; grep -Rin -- "$q" /var/log 2>/dev/null >"$TMP_DIR/log-search" || true; ui_text Logs "$(tail -n 300 "$TMP_DIR/log-search")";; follow) f=$(ui_input Logs 'Log file:' '/var/log/syslog') || continue; tail -n 100 -f "$f";; rotate) run_capture Logs as_root logrotate -f /etc/logrotate.conf;; clean) log_cleanup_wizard;; syslog) logging_install_syslog;; project) ui_text Project "$(tail -n 300 "$LOG_FILE")";; esac; done; }
log_cleanup_wizard(){ days=$(ui_input Logs 'Delete compressed/rotated logs older than days:' '30') || return; ui_yesno Logs "Delete old rotated logs under /var/log?" || return; run_capture Logs as_root find /var/log -type f -mtime +"$days" \( -name '*.gz' -o -name '*.old' -o -name '*.[0-9]' \) -delete; }
logging_install_syslog(){ c=$(ui_menu Syslog 'Choose implementation.' rsyslog rsyslog syslogng syslog-ng busybox 'BusyBox syslog') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in rsyslog) pkg=rsyslog;; syslogng) pkg=syslog-ng;; busybox) pkg=busybox;; esac; run_capture Syslog pkg_install "$pkg"; }

aok_builder_studio(){ while :; do c=$(ui_menu 'AOK Builder Studio' "Active rootfs: $(active_rootfs)" create 'Distribution/rootfs builders' recipes 'Recipe and manifest tools' overlays 'Overlay management' queue 'Build queue manager' artifacts 'Build artifacts and archives' validate 'Preflight and integrity validation' compare 'Compare rootfs instances' optimize 'Optimize active rootfs' mounts 'Chroot mount profiles' existing 'Complete AOK control center') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in create) aok_build_menu;; recipes) aok_more_options_menu;; overlays) aok_more_options_menu;; queue) aok_build_queue_menu;; artifacts) aok_filesystems_menu;; validate) aok_advanced_tools_menu;; compare) aok_filesystems_menu;; optimize) aok_optimize_sync_menu;; mounts) mount_profile_menu rootfs;; existing) aok_menu;; esac; done; }
aok_build_queue_menu(){ q=$STATE_DIR/aok-build-queue.tsv; touch "$q"; c=$(ui_menu 'Build queue' 'Store build commands for repeatable execution.' list 'List queued commands' add 'Add command' run 'Run queue sequentially' clear 'Clear queue') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in list) ui_text Queue "$(nl -ba "$q" 2>/dev/null)";; add) name=$(ui_input Queue 'Job name:' '') || return; cmd=$(ui_input Queue 'Build command:' '') || return; printf '%s|%s\n' "$name" "$cmd" >>"$q";; run) while IFS='|' read -r name cmd; do [ -n "$cmd" ] || continue; run_capture "Build queue: $name" sh -c "$cmd" || break; done <"$q";; clear) : >"$q";; esac; }

package_center_v6(){ while :; do c=$(ui_menu 'Package center' "Package manager: $PKG_MGR" existing 'Existing package manager' installed 'List installed packages' files 'Show files owned by package' owner 'Find package owning a file' deps 'Dependency information' reverse 'Reverse dependencies' reinstall 'Reinstall package' hold 'Hold or pin package' unhold 'Remove hold' orphan 'List or clean orphan packages' repair 'Repair package database' history 'Package history and logs') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in existing) package_menu;; installed) package_installed_report;; files) package_files_report;; owner) package_owner_report;; deps) package_dependency_report normal;; reverse) package_dependency_report reverse;; reinstall) package_reinstall;; hold) package_hold yes;; unhold) package_hold no;; orphan) package_orphan_menu;; repair) package_repair_v6;; history) package_history_report;; esac; done; }
package_installed_report(){ case $PKG_MGR in apt) cmd='dpkg-query -W';; apk) cmd='apk info -vv';; pacman) cmd='pacman -Q';; dnf|yum) cmd='rpm -qa';; xbps) cmd='xbps-query -l';; emerge) cmd='qlist -Iv';; zypper) cmd='rpm -qa';; *) cmd='true';; esac; v6_command_output Packages sh -c "$cmd"; }
package_files_report(){ p=$(ui_input Package 'Package name:' '') || return; case $PKG_MGR in apt) cmd="dpkg -L '$p'";; apk) cmd="apk info -L '$p'";; pacman) cmd="pacman -Ql '$p'";; dnf|yum|zypper) cmd="rpm -ql '$p'";; xbps) cmd="xbps-query -f '$p'";; esac; v6_command_output Package sh -c "$cmd"; }
package_owner_report(){ f=$(ui_input Package 'File path:' '') || return; case $PKG_MGR in apt) cmd="dpkg -S '$f'";; apk) cmd="apk info --who-owns '$f'";; pacman) cmd="pacman -Qo '$f'";; dnf|yum|zypper) cmd="rpm -qf '$f'";; xbps) cmd="xbps-query -o '$f'";; esac; v6_command_output Owner sh -c "$cmd"; }
package_dependency_report(){ mode=$1; p=$(ui_input Package 'Package name:' '') || return; case $PKG_MGR:$mode in apt:normal) cmd="apt-cache depends '$p'";; apt:reverse) cmd="apt-cache rdepends '$p'";; apk:normal) cmd="apk info -R '$p'";; apk:reverse) cmd="apk info -r '$p'";; pacman:normal) cmd="pactree '$p'";; pacman:reverse) cmd="pactree -r '$p'";; dnf:normal|yum:normal) cmd="$PKG_MGR repoquery --requires '$p'";; dnf:reverse|yum:reverse) cmd="$PKG_MGR repoquery --whatrequires '$p'";; *) cmd='true';; esac; v6_command_output Dependencies sh -c "$cmd"; }
package_reinstall(){ p=$(ui_input Package 'Package name:' '') || return; case $PKG_MGR in apt) run_capture Package as_root apt-get install --reinstall -y "$p";; apk) run_capture Package as_root apk fix "$p";; pacman) run_capture Package as_root pacman -S --noconfirm "$p";; dnf|yum) run_capture Package as_root "$PKG_MGR" reinstall -y "$p";; xbps) run_capture Package as_root xbps-install -f "$p";; esac; }
package_hold(){ state=$1; p=$(ui_input Package 'Package name:' '') || return; case $PKG_MGR:$state in apt:yes) run_capture Package as_root apt-mark hold "$p";; apt:no) run_capture Package as_root apt-mark unhold "$p";; apk:yes) append_unique /etc/apk/world "$p";; pacman:yes) ui_msg Package 'Use IgnorePkg in /etc/pacman.conf; the native adapter can edit it.';; dnf:yes|yum:yes) run_capture Package as_root "$PKG_MGR" versionlock add "$p";; dnf:no|yum:no) run_capture Package as_root "$PKG_MGR" versionlock delete "$p";; *) ui_msg Package 'Hold operation is not implemented for this manager.';; esac; }
package_orphan_menu(){ case $PKG_MGR in apt) cmd='apt-get autoremove --dry-run'; clean='apt-get autoremove -y';; apk) cmd='apk info -O'; clean='true';; pacman) cmd='pacman -Qtdq'; clean='pacman -Rns --noconfirm $(pacman -Qtdq)';; dnf|yum) cmd="$PKG_MGR repoquery --unneeded"; clean="$PKG_MGR autoremove -y";; xbps) cmd='xbps-query -O'; clean='xbps-remove -o';; esac; v6_command_output Orphans sh -c "$cmd"; ui_yesno Orphans 'Run orphan cleanup?' && run_capture Orphans as_root sh -c "$clean"; }
package_repair_v6(){ case $PKG_MGR in apt) run_capture Repair as_root dpkg --configure -a; run_capture Repair as_root apt-get -f install -y;; apk) run_capture Repair as_root apk fix;; pacman) run_capture Repair as_root pacman -Dk;; dnf|yum) run_capture Repair as_root "$PKG_MGR" check;; xbps) run_capture Repair as_root xbps-pkgdb -a;; esac; }
package_history_report(){ v6_command_output History sh -c 'tail -n 300 /var/log/apt/history.log /var/log/dpkg.log /var/log/pacman.log /var/log/dnf.log /var/log/zypp/history 2>/dev/null'; }

service_center_v6(){ while :; do c=$(ui_menu 'Service center' "Detected init: $INIT_SYSTEM" existing 'Existing service manager' status 'Common service status' named 'Manage named service' enabled 'List enabled services' failed 'Find failed or stale services' scripts 'Browse init scripts' dependencies 'Service dependency hints' profile 'Apply minimal/SSH/developer service profile' convert 'Systemd compatibility and conversion tools') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in existing) services_menu;; status) services_menu;; named) service_manage;; enabled) services_menu;; failed) service_failed_report;; scripts) v6_command_output Services sh -c 'find /etc/init.d /etc/rc.d /etc/sv -maxdepth 2 -type f 2>/dev/null';; dependencies) v6_command_output Services sh -c 'grep -R "Required-Start\|need \|use \|after " /etc/init.d /etc/conf.d 2>/dev/null | head -n 300';; profile) service_profile_wizard;; convert) init_system_menu;; esac; done; }
service_failed_report(){ v6_command_output Services sh -c 'systemctl --failed 2>/dev/null; rc-status 2>/dev/null; service --status-all 2>/dev/null'; }
service_profile_wizard(){ p=$(ui_menu Services 'Choose a service profile.' minimal 'Minimal' ssh 'SSH server' developer 'Developer') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $p in minimal) disable='bluetooth cups avahi-daemon ModemManager';; ssh) disable='bluetooth cups avahi-daemon'; service_enable ssh 2>/dev/null || service_enable sshd 2>/dev/null || true;; developer) disable='bluetooth cups';; esac; for s in $disable; do service_disable "$s" 2>/dev/null || true; done; ui_msg Services "Applied profile: $p"; }

shell_center_v6(){ while :; do c=$(ui_menu 'Shell center' 'Selectable shell and prompt configuration.' existing 'Existing shell wizards' defaults 'Generate default shell configuration' aliases 'Aliases and managed additions' prompt 'Prompt and Starship configuration' login 'Default login shell' inspect 'Inspect installed shells') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in existing) shells_menu;; defaults) shell_defaults_menu;; aliases) shell_add_menu;; prompt) config_target_menu Starship "$CURRENT_HOME/.config/starship.toml" starship_wizard starship;; login) user_shell_wizard;; inspect) ui_text Shells "$(cat /etc/shells 2>/dev/null; printf '\nInstalled:\n'; for s in sh ash bash zsh fish ksh; do command -v "$s" 2>/dev/null; done)";; esac; done; }
editor_center_v6(){ while :; do c=$(ui_menu 'Editor center' 'Selectable editor and language tooling.' existing 'Existing editor wizards' default 'Set default editor variables' lsp 'Language-server installer' formatters 'Formatter installer' inspect 'Installed editor versions') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in existing) editors_menu;; default) editor_default_profile;; lsp) editor_lsp_installer;; formatters) editor_formatter_installer;; inspect) v6_command_output Editors sh -c 'for e in nano vim nvim micro hx emacs kak vis joe; do command -v "$e" >/dev/null && "$e" --version 2>&1 | head -n 2; done';; esac; done; }
editor_default_profile(){ e=$(ui_menu Editor 'Choose default editor.' nano Nano vim Vim nvim Neovim micro Micro hx Helix vi vi) || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; replace_block "$CURRENT_HOME/.profile" default-editor "export EDITOR='$e'\nexport VISUAL='$e'"; }
editor_lsp_installer(){ choices=$(ui_checklist LSP 'Select language-server packages.' bash 'bash-language-server' off clang 'clangd' off python 'pyright' off rust 'rust-analyzer' off go 'gopls' off yaml 'yaml-language-server' off json 'vscode-json-languageserver' off) || return; for x in $choices; do case $x in bash) pkg='bash-language-server';; clang) pkg='clangd';; python) pkg='pyright';; rust) pkg='rust-analyzer';; go) pkg='gopls';; yaml) pkg='yaml-language-server';; json) pkg='vscode-json-languageserver';; esac; run_capture LSP pkg_install "$pkg" || true; done; }
editor_formatter_installer(){ p=$(ui_input Formatter 'Space-separated formatter packages:' 'shfmt black prettier clang-format') || return; run_capture Formatter pkg_install $p; }
terminal_center_v6(){ while :; do c=$(ui_menu 'Terminal center' 'Terminal environment and multiplexer configuration.' existing 'Existing terminal wizards' tmux 'Tmux configuration' screen 'GNU Screen configuration' readline 'Readline keybindings' colors 'Terminal capability and color report' osc52 'Install OSC52 clipboard helper' profile 'Terminal environment profile') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in existing) terminal_tools_menu;; tmux) tmux_config_wizard 2>/dev/null || terminal_tools_menu;; screen) screen_config_wizard 2>/dev/null || terminal_tools_menu;; readline) inputrc_config_wizard 2>/dev/null || config_files_menu;; colors) terminal_capability_report;; osc52) terminal_install_osc52;; profile) terminal_environment_wizard 2>/dev/null || terminal_tools_menu;; esac; done; }
terminal_capability_report(){ v6_command_output Terminal sh -c 'printf "TERM=%s\nCOLORTERM=%s\n" "$TERM" "${COLORTERM:-}"; command -v infocmp >/dev/null && infocmp "$TERM"; command -v tput >/dev/null && { printf "colors="; tput colors; }'; }
terminal_install_osc52(){ d=$CURRENT_HOME/.local/bin; mkdir -p "$d"; cat >"$d/osc52-copy" <<'EOS'
#!/bin/sh
base64 | tr -d '\n' | awk '{printf "\033]52;c;%s\a",$0}'
EOS
chmod 755 "$d/osc52-copy"; ui_msg OSC52 "$d/osc52-copy"; }
file_manager_center_v6(){ while :; do c=$(ui_menu 'File manager center' 'CLI file managers, integrations and previews.' existing 'Existing file-manager wizards' install 'Install selected file managers' defaults 'Set preferred file manager' inspect 'Installed versions') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in existing) file_managers_menu;; install) p=$(ui_checklist Files 'Select file managers.' nnn nnn off lf lf off ranger ranger off yazi yazi off mc 'Midnight Commander' off vifm vifm off broot broot off) || continue; [ -n "$p" ] && run_capture Files pkg_install $p;; defaults) f=$(ui_menu Files 'Preferred terminal file manager.' nnn nnn lf lf ranger Ranger yazi Yazi mc 'Midnight Commander' vifm vifm) || continue; replace_block "$CURRENT_HOME/.profile" file-manager "export FILE_MANAGER='$f'";; inspect) v6_command_output Files sh -c 'for f in nnn lf ranger yazi mc vifm broot; do command -v "$f" >/dev/null && { printf "%s: " "$f"; "$f" --version 2>&1 | head -n 1; }; done';; esac; done; }

recovery_center(){ while :; do c=$(ui_menu 'Boot and recovery center' 'Recovery reports and rollback helpers. Bootloader options may not apply to iSH-AOK.' snapshot 'Create configuration snapshot' backups 'List project backups' init 'Init-system recovery tools' mounts 'Unmount stale rootfs mounts' packages 'Repair package database' shell 'Generate rescue shell script' report 'Create recovery report' restore 'Restore a selected backup file') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in snapshot) backup_common;; backups) ui_text Backups "$(ls -lht "$BACKUP_DIR" 2>/dev/null)";; init) init_system_menu;; mounts) aok_chroot_menu;; packages) package_repair_v6;; shell) recovery_shell_script;; report) recovery_report;; restore) backup_restore_center;; esac; done; }
recovery_shell_script(){ f=$CURRENT_HOME/ish-aok-rescue.sh; cat >"$f" <<'EOS'
#!/bin/sh
set -u
export PATH=/usr/sbin:/usr/bin:/sbin:/bin
mount -t proc proc /proc 2>/dev/null || true
mount -t sysfs sysfs /sys 2>/dev/null || true
mount -t devpts devpts /dev/pts 2>/dev/null || true
exec /bin/sh -i
EOS
chmod 755 "$f"; ui_msg Recovery "$f"; }
recovery_report(){ out=$REPORT_DIR/recovery-$(date +%Y%m%d-%H%M%S).txt; { uname -a; cat /etc/os-release 2>/dev/null; ps -p 1 -o pid,comm,args 2>/dev/null; mount; df -h; cat /proc/meminfo 2>/dev/null; command -v dpkg >/dev/null && dpkg --audit; command -v apk >/dev/null && apk audit --recursive; } >"$out" 2>&1; ui_msg Recovery "$out"; }
security_center_v6(){ while :; do c=$(ui_menu 'Security center' 'Permission, privilege, SSH and secret-management tools.' existing 'Existing security audits' permissions 'Permission audit' sudo 'Sudo and doas management' ssh 'SSH hardening and keys' secrets 'Scan paths for possible secrets' listeners 'Listening network services' hashes 'Generate file checksum' integrity 'Rootfs integrity tools') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in existing) security_tools_menu;; permissions) permission_audit;; sudo) privilege_admin_menu;; ssh) ssh_menu;; secrets) security_secret_scan;; listeners) v6_command_output Security sh -c 'ss -lntup 2>/dev/null || netstat -lntup 2>/dev/null';; hashes) f=$(ui_input Hash 'File:' '') || continue; v6_command_output Hash sha256sum "$f";; integrity) aok_advanced_tools_menu;; esac; done; }
security_secret_scan(){ p=$(ui_input Security 'Path to scan:' "$CURRENT_HOME") || return; out=$REPORT_DIR/secret-scan-$(date +%Y%m%d-%H%M%S).txt; grep -RInE 'BEGIN (RSA|OPENSSH|EC) PRIVATE KEY|api[_-]?key|secret[_-]?key|password[[:space:]]*=' "$p" 2>/dev/null | head -n 500 >"$out" || true; ui_text Security "$(cat "$out")"; }
developer_center_v6(){ while :; do c=$(ui_menu 'Developer center' 'Compilers, language ecosystems and reproducible-build helpers.' build 'Build systems and compilers' languages 'Language ecosystems' tools 'General development tools' profiles 'Compiler and build profiles' linker 'Dynamic linker and pkg-config audit' cache 'Compiler-cache status' cross 'Cross-compilation readiness') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in build) build_compilers_menu;; languages) languages_menu;; tools) development_menu;; profiles) profiles_bundles_menu;; linker) developer_linker_report;; cache) v6_command_output ccache sh -c 'ccache -s 2>/dev/null; sccache --show-stats 2>/dev/null';; cross) developer_cross_report;; esac; done; }
developer_linker_report(){ v6_command_output Linker sh -c 'printf "PATH=%s\nPKG_CONFIG_PATH=%s\nLD_LIBRARY_PATH=%s\n" "$PATH" "${PKG_CONFIG_PATH:-}" "${LD_LIBRARY_PATH:-}"; ldconfig -p 2>/dev/null | head -n 200; pkg-config --list-all 2>/dev/null | head -n 200'; }
developer_cross_report(){ v6_command_output Cross sh -c 'uname -m; for c in gcc clang rustc cargo go qemu-aarch64-static qemu-x86_64-static qemu-riscv64-static; do command -v "$c" >/dev/null && printf "%s=%s\n" "$c" "$(command -v "$c")"; done'; }
