#!/bin/sh
# v9.4 Cross-Distribution Build Matrix UI
v94_select_matrix(){ set --; for f in "$V94_MATRIX_DIR"/*.matrix; do [ -f "$f" ] || continue; id=$(basename "$f" .matrix); set -- "$@" "$id" "$(grep -vc '^#' "$f" 2>/dev/null || echo 0) target(s)"; done; [ "$#" -gt 0 ] || return 1; c=$(ui_menu 'Build matrices' 'Select a matrix.' "$@") || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return 1; }; printf '%s/%s.matrix\n' "$V94_MATRIX_DIR" "$c"; }
v94_matrix_new_ui(){ name=$(ui_input 'New build matrix' 'Matrix name:' 'cross-distribution') || return; f=$(v94_matrix_create "$name") || return; ui_msg 'Build matrix' "Created: $f"; }
v94_matrix_add_ui(){ f=$(v94_select_matrix) || { ui_msg 'Build matrix' 'Create a matrix first.'; return; }; p=$(v89_profile_select_file "$V89_PROFILE_LIBRARY" 'Select profile') || p=$V87_BUILD_PROFILE; d=$(ui_input 'Matrix target' 'Distribution:' "$(v87_profile_get "$p" DISTRO)") || return; r=$(ui_input 'Matrix target' 'Release:' "$(v87_profile_get "$p" RELEASE)") || return; a=$(ui_input 'Matrix target' 'Architecture:' "$(v87_profile_get "$p" ARCH)") || return; v94_matrix_add "$f" "$p" "$d" "$r" "$a"; ui_msg 'Build matrix' 'Target added.'; }
v94_matrix_studio(){ v94_install_templates; while :; do c=$(ui_menu 'Cross-Distribution Build Matrix' 'Compose and execute repeatable multi-distribution RootFS builds.' new 'Create matrix' add 'Add target to matrix' plan 'Review matrix plan' validate 'Validate matrix' execute 'Execute matrix sequentially' templates 'List build templates' capabilities 'Builder capability report' packages 'Package-group mappings' plugins 'Plugin builder directory') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in new) v94_matrix_new_ui;; add) v94_matrix_add_ui;; plan) f=$(v94_select_matrix) && ui_text 'Matrix plan' "$(v94_matrix_plan "$f")";; validate) f=$(v94_select_matrix) && ui_text 'Matrix validation' "$(v94_matrix_validate "$f" 2>&1 || true)";; execute) f=$(v94_select_matrix) && ui_yesno 'Execute matrix' 'Run every pending target sequentially?' && v94_matrix_execute "$f";; templates) ui_text 'Build templates' "$(find "$V94_TEMPLATE_DIR" -name '*.profile' -maxdepth 1 -type f 2>/dev/null | sed 's#.*/##;s#\.profile$##')";; capabilities) ui_text 'Builder capabilities' "$(v94_capability_report)";; packages) ui_text 'Package groups' "$(find "$V94_GROUP_DIR" -name '*.map' -maxdepth 1 -type f 2>/dev/null | sed 's#.*/##;s#\.map$##')";; plugins) ui_msg 'Plugin builders' "Install .builder manifests in:\n$V94_PLUGIN_BUILDER_DIR";; esac; done; }

# Extend canonical Build Studio with matrix entry.
aok_builder_studio(){ while :; do c=$(ui_menu 'RootFS Build Studio' "Active RootFS: $(active_rootfs)" profiles 'Build profiles and distribution presets' matrix 'Cross-distribution build matrix' paths 'Build sources, destinations and artifacts' execution 'Build execution, resume and recovery' recipes 'Build recipes and queue' projects 'RootFS projects' import 'Builder backends and RootFS import' validate 'Compatibility and preflight tools' artifacts 'Artifacts, archives and exports' overlays 'Overlay management' reports 'Build reports and logs') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; }; case $c in profiles) v89_profile_manager_menu;; matrix) v94_matrix_studio;; paths) v93_paths_menu;; execution) v88_build_execution_menu;; recipes) v89_recipes_queue_menu;; projects) rootfs_projects_menu;; import) aok_build_menu;; validate) aok_advanced_tools_menu;; artifacts) rootfs_import_export_studio;; overlays) overlay_studio_menu_v72 2>/dev/null || aok_more_options_menu;; reports) aok_build_logs;; esac; done; }
v94_matrix_report_cli(){ v94_install_templates; v94_install_package_groups; v94_matrix_report; }
