#!/bin/sh

V91_DOC_DIR=${V91_DOC_DIR:-$REPORT_DIR/developer-v91}
V91_CONFIG_DIR=${V91_CONFIG_DIR:-${ISH_AOK_CONFIG_ROOT:-.}/config}
mkdir -p "$V91_DOC_DIR" 2>/dev/null || true

v91_config_load(){
  for f in "$V91_CONFIG_DIR"/*.conf; do [ -r "$f" ] && . "$f"; done
}
v91_refresh_workspace(){ detect_system; scan_system >/dev/null 2>&1 || true; activity_add workspace 'Refreshed workspace'; }
v91_build_validate_ui(){ ui_text 'Build profile validation' "$(v89_profile_validate_report)"; }
v91_build_plan_ui(){ ui_text 'Build plan' "$(v88_build_plan_report)"; }
v91_workspace_report_ui(){ ui_text 'Workspace report' "$(workspace_report_v91)"; }
v91_distribution_report_ui(){ root=$(v90_active_rootfs); out=$(v84_distribution_report "$root"); ui_text Distribution "$(cat "$out")"; }
v91_service_report_ui(){ root=$(v90_active_rootfs); out=$(service_v85_report "$root"); ui_text Services "$(cat "$out")"; }
v91_repository_report_ui(){ root=$(v90_active_rootfs); out=$(repo_v86_report "$root"); ui_text Repositories "$(cat "$out")"; }
v91_platform_report_ui(){ ui_text Platform "$(platform_v80_report)"; }

v91_generate_developer_docs(){
  mkdir -p "$V91_DOC_DIR" 2>/dev/null || return 1
  menu_doc=$V91_DOC_DIR/MENUS.md
  api_doc=$V91_DOC_DIR/REGISTRATION_API.md
  module_doc=$V91_DOC_DIR/MODULES.md
  {
    printf '# Declarative Menus\n\nGenerated by iSH-AOK Config %s.\n\n' "$VERSION"
    for f in "$V91_MENU_DIR"/*.menu; do
      [ -f "$f" ] || continue
      printf '## %s\n\n| ID | Label | Handler | Description |\n|---|---|---|---|\n' "$(basename "$f" .menu)"
      while IFS='|' read -r id label handler description; do case $id in ''|'#'*) continue;; esac; printf '| `%s` | %s | `%s` | %s |\n' "$id" "$label" "$handler" "$description"; done <"$f"
      printf '\n'
    done
  } >"$menu_doc"
  cat >"$api_doc" <<'DOC'
# Registration API

Modules may register features without editing the main application:

```sh
register_menu MENU ID LABEL HANDLER DESCRIPTION
register_action ID LABEL CATEGORY HANDLER DESCRIPTION
register_report ID LABEL HANDLER DESCRIPTION
register_workflow ID WORKFLOW_FILE
register_builder ID LABEL HANDLER DESCRIPTION
```

Handlers remain ordinary POSIX shell functions. Menu files use:

```text
id|label|handler|description
```

Special handlers are `@menu:name`, `@action:id`, and `@return`.
DOC
  {
    printf '# Module Inventory\n\n'
    for f in "${ISH_AOK_CONFIG_ROOT:-.}"/modules/*.sh "${ISH_AOK_CONFIG_ROOT:-.}"/modules/*/*.sh; do [ -f "$f" ] && printf -- '- `%s`\n' "${f#${ISH_AOK_CONFIG_ROOT:-.}/}"; done
  } >"$module_doc"
  printf '%s\n%s\n%s\n' "$menu_doc" "$api_doc" "$module_doc"
}

v91_architecture_report(){
  printf '%s %s — Modular Core\n\n' "$PROGRAM" "$VERSION"
  printf 'Menu definitions: %s\n' "$(find "$V91_MENU_DIR" -name '*.menu' -type f 2>/dev/null | wc -l | tr -d ' ')"
  printf 'Modules: %s\n' "$(find "${ISH_AOK_CONFIG_ROOT:-.}/modules" -name '*.sh' -type f 2>/dev/null | wc -l | tr -d ' ')"
  printf 'Configuration groups: %s\n' "$(find "$V91_CONFIG_DIR" -name '*.conf' -type f 2>/dev/null | wc -l | tr -d ' ')"
  printf 'Test runner: %s\n' "${ISH_AOK_CONFIG_ROOT:-.}/tests/run-all.sh"
  printf 'Generated documentation: %s\n' "$V91_DOC_DIR"
  printf 'Menu validation: '
  v91_menu_validate >/dev/null 2>&1 && printf 'pass\n' || printf 'fail\n'
}

v91_developer_center(){
  while :; do
    c=$(ui_menu 'Developer Architecture' 'Modular core, declarative menus, documentation and tests.' report 'Architecture report' menus 'Validate declarative menus' docs 'Generate developer documentation' tests 'Run complete test suite' config 'Open configuration directory') || { _menu_rc=$?; [ "$_menu_rc" -eq "${UI_MENU_BACK_RC:-90}" ] && return 0; return "$_menu_rc"; };
    case $c in
      report) ui_text Architecture "$(v91_architecture_report)";;
      menus) if v91_menu_validate; then ui_msg Menus 'All declarative menu handlers are valid.'; else ui_msg Menus 'Menu validation failed. Review terminal output.'; fi;;
      docs) files=$(v91_generate_developer_docs) && ui_text Documentation "$files";;
      tests) run_capture 'Project test suite' sh "${ISH_AOK_CONFIG_ROOT:-.}/tests/run-all.sh";;
      config) ui_text Configuration "$(find "$V91_CONFIG_DIR" -maxdepth 1 -type f -print 2>/dev/null)";;
    esac
  done
}

rootfs_explorer_menu(){ v91_menu_run rootfs; }
unified_build_menu(){ v91_menu_run build; }
workspace_dashboard_v91(){ v91_menu_run workspace; }
workspace_report_v91(){
  command_registry_build
  printf 'iSH-AOK Workspace — Unified Workspace\n'
  printf 'Modular Core: v9.1 declarative navigation\n\n%s\n' "$(v90_workspace_summary)"
  printf 'Registered actions: %s\n' "$(awk 'END{print NR+0}' "$V73_ACTIONS_FILE")"
  printf 'Declarative menus: %s\n' "$(find "$V91_MENU_DIR" -name '*.menu' -type f 2>/dev/null | wc -l | tr -d ' ')"
  awk -F '\t' '{printf "%-20s %-14s %s\n",$1,$3,$2}' "$V73_ACTIONS_FILE"
}

# Override v9.0 hard-coded workspace entry points while retaining their names.
v90_rootfs_actions_menu(){ v91_menu_run rootfs; }
v90_build_workflow_menu(){ v91_menu_run build; }
v90_administration_menu(){ v91_menu_run administration; }
v90_reports_menu(){ v91_menu_run main; }
v90_settings_menu(){ v91_menu_run settings; }
workspace_dashboard_v90(){ workspace_dashboard_v91; }
workspace_report_v90(){ workspace_report_v91; }
main_menu(){ v91_config_load; workspace_dashboard_v91; }

command_registry_build(){
  command_registry_build_base
  printf '%s\t%s\t%s\t%s\t%s\n' architecture 'Developer architecture' Development v91_developer_center 'Modular menus, docs and tests' >>"$V73_ACTIONS_FILE"
  printf '%s\t%s\t%s\t%s\t%s\n' architecture_report 'Architecture report' Reports v91_architecture_report 'v9.1 modular-core status' >>"$V73_ACTIONS_FILE"
}
